package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class ActivitiesCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F383, false),
      new GoogleCompatEmoji(0x1F384, false),
      new GoogleCompatEmoji(0x1F386, false),
      new GoogleCompatEmoji(0x1F387, false),
      new GoogleCompatEmoji(0x1F9E8, false),
      new GoogleCompatEmoji(0x2728, false),
      new GoogleCompatEmoji(0x1F388, false),
      new GoogleCompatEmoji(0x1F389, false),
      new GoogleCompatEmoji(0x1F38A, false),
      new GoogleCompatEmoji(0x1F38B, false),
      new GoogleCompatEmoji(0x1F38D, false),
      new GoogleCompatEmoji(0x1F38E, false),
      new GoogleCompatEmoji(0x1F38F, false),
      new GoogleCompatEmoji(0x1F390, false),
      new GoogleCompatEmoji(0x1F391, false),
      new GoogleCompatEmoji(0x1F9E7, false),
      new GoogleCompatEmoji(0x1F380, false),
      new GoogleCompatEmoji(0x1F381, false),
      new GoogleCompatEmoji(new int[] { 0x1F397, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F39F, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3AB, false),
      new GoogleCompatEmoji(new int[] { 0x1F396, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3C6, false),
      new GoogleCompatEmoji(0x1F3C5, false),
      new GoogleCompatEmoji(0x1F947, false),
      new GoogleCompatEmoji(0x1F948, false),
      new GoogleCompatEmoji(0x1F949, false),
      new GoogleCompatEmoji(0x26BD, false),
      new GoogleCompatEmoji(0x26BE, false),
      new GoogleCompatEmoji(0x1F94E, false),
      new GoogleCompatEmoji(0x1F3C0, false),
      new GoogleCompatEmoji(0x1F3D0, false),
      new GoogleCompatEmoji(0x1F3C8, false),
      new GoogleCompatEmoji(0x1F3C9, false),
      new GoogleCompatEmoji(0x1F3BE, false),
      new GoogleCompatEmoji(0x1F94F, false),
      new GoogleCompatEmoji(0x1F3B3, false),
      new GoogleCompatEmoji(0x1F3CF, false),
      new GoogleCompatEmoji(0x1F3D1, false),
      new GoogleCompatEmoji(0x1F3D2, false),
      new GoogleCompatEmoji(0x1F94D, false),
      new GoogleCompatEmoji(0x1F3D3, false),
      new GoogleCompatEmoji(0x1F3F8, false),
      new GoogleCompatEmoji(0x1F94A, false),
      new GoogleCompatEmoji(0x1F94B, false),
      new GoogleCompatEmoji(0x1F945, false),
      new GoogleCompatEmoji(0x26F3, false),
      new GoogleCompatEmoji(new int[] { 0x26F8, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3A3, false),
      new GoogleCompatEmoji(0x1F93F, false),
      new GoogleCompatEmoji(0x1F3BD, false),
      new GoogleCompatEmoji(0x1F3BF, false),
      new GoogleCompatEmoji(0x1F6F7, false),
      new GoogleCompatEmoji(0x1F94C, false),
      new GoogleCompatEmoji(0x1F3AF, false),
      new GoogleCompatEmoji(0x1FA80, false),
      new GoogleCompatEmoji(0x1FA81, false),
      new GoogleCompatEmoji(0x1F3B1, false),
      new GoogleCompatEmoji(0x1F52E, false),
      new GoogleCompatEmoji(0x1F9FF, false),
      new GoogleCompatEmoji(0x1F3AE, false),
      new GoogleCompatEmoji(new int[] { 0x1F579, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3B0, false),
      new GoogleCompatEmoji(0x1F3B2, false),
      new GoogleCompatEmoji(0x1F9E9, false),
      new GoogleCompatEmoji(0x1F9F8, false),
      new GoogleCompatEmoji(new int[] { 0x2660, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2665, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2666, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2663, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x265F, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F0CF, false),
      new GoogleCompatEmoji(0x1F004, false),
      new GoogleCompatEmoji(0x1F3B4, false),
      new GoogleCompatEmoji(0x1F3AD, false),
      new GoogleCompatEmoji(new int[] { 0x1F5BC, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3A8, false),
      new GoogleCompatEmoji(0x1F9F5, false),
      new GoogleCompatEmoji(0x1F9F6, false)
    };
  }

  private ActivitiesCategoryChunk0() {
    // No instances.
  }
}
