package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class ActivitiesCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F383, new String[]{"jack_o_lantern"}, false),
      new GoogleCompatEmoji(0x1F384, new String[]{"christmas_tree"}, false),
      new GoogleCompatEmoji(0x1F386, new String[]{"fireworks"}, false),
      new GoogleCompatEmoji(0x1F387, new String[]{"sparkler"}, false),
      new GoogleCompatEmoji(0x1F9E8, new String[]{"firecracker"}, false),
      new GoogleCompatEmoji(0x2728, new String[]{"sparkles"}, false),
      new GoogleCompatEmoji(0x1F388, new String[]{"balloon"}, false),
      new GoogleCompatEmoji(0x1F389, new String[]{"tada"}, false),
      new GoogleCompatEmoji(0x1F38A, new String[]{"confetti_ball"}, false),
      new GoogleCompatEmoji(0x1F38B, new String[]{"tanabata_tree"}, false),
      new GoogleCompatEmoji(0x1F38D, new String[]{"bamboo"}, false),
      new GoogleCompatEmoji(0x1F38E, new String[]{"dolls"}, false),
      new GoogleCompatEmoji(0x1F38F, new String[]{"flags"}, false),
      new GoogleCompatEmoji(0x1F390, new String[]{"wind_chime"}, false),
      new GoogleCompatEmoji(0x1F391, new String[]{"rice_scene"}, false),
      new GoogleCompatEmoji(0x1F9E7, new String[]{"red_envelope"}, false),
      new GoogleCompatEmoji(0x1F380, new String[]{"ribbon"}, false),
      new GoogleCompatEmoji(0x1F381, new String[]{"gift"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F397, 0xFE0F }, new String[]{"reminder_ribbon"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F39F, 0xFE0F }, new String[]{"admission_tickets"}, false),
      new GoogleCompatEmoji(0x1F3AB, new String[]{"ticket"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F396, 0xFE0F }, new String[]{"medal"}, false),
      new GoogleCompatEmoji(0x1F3C6, new String[]{"trophy"}, false),
      new GoogleCompatEmoji(0x1F3C5, new String[]{"sports_medal"}, false),
      new GoogleCompatEmoji(0x1F947, new String[]{"first_place_medal"}, false),
      new GoogleCompatEmoji(0x1F948, new String[]{"second_place_medal"}, false),
      new GoogleCompatEmoji(0x1F949, new String[]{"third_place_medal"}, false),
      new GoogleCompatEmoji(0x26BD, new String[]{"soccer"}, false),
      new GoogleCompatEmoji(0x26BE, new String[]{"baseball"}, false),
      new GoogleCompatEmoji(0x1F94E, new String[]{"softball"}, false),
      new GoogleCompatEmoji(0x1F3C0, new String[]{"basketball"}, false),
      new GoogleCompatEmoji(0x1F3D0, new String[]{"volleyball"}, false),
      new GoogleCompatEmoji(0x1F3C8, new String[]{"football"}, false),
      new GoogleCompatEmoji(0x1F3C9, new String[]{"rugby_football"}, false),
      new GoogleCompatEmoji(0x1F3BE, new String[]{"tennis"}, false),
      new GoogleCompatEmoji(0x1F94F, new String[]{"flying_disc"}, false),
      new GoogleCompatEmoji(0x1F3B3, new String[]{"bowling"}, false),
      new GoogleCompatEmoji(0x1F3CF, new String[]{"cricket_bat_and_ball"}, false),
      new GoogleCompatEmoji(0x1F3D1, new String[]{"field_hockey_stick_and_ball"}, false),
      new GoogleCompatEmoji(0x1F3D2, new String[]{"ice_hockey_stick_and_puck"}, false),
      new GoogleCompatEmoji(0x1F94D, new String[]{"lacrosse"}, false),
      new GoogleCompatEmoji(0x1F3D3, new String[]{"table_tennis_paddle_and_ball"}, false),
      new GoogleCompatEmoji(0x1F3F8, new String[]{"badminton_racquet_and_shuttlecock"}, false),
      new GoogleCompatEmoji(0x1F94A, new String[]{"boxing_glove"}, false),
      new GoogleCompatEmoji(0x1F94B, new String[]{"martial_arts_uniform"}, false),
      new GoogleCompatEmoji(0x1F945, new String[]{"goal_net"}, false),
      new GoogleCompatEmoji(0x26F3, new String[]{"golf"}, false),
      new GoogleCompatEmoji(new int[] { 0x26F8, 0xFE0F }, new String[]{"ice_skate"}, false),
      new GoogleCompatEmoji(0x1F3A3, new String[]{"fishing_pole_and_fish"}, false),
      new GoogleCompatEmoji(0x1F93F, new String[]{"diving_mask"}, false),
      new GoogleCompatEmoji(0x1F3BD, new String[]{"running_shirt_with_sash"}, false),
      new GoogleCompatEmoji(0x1F3BF, new String[]{"ski"}, false),
      new GoogleCompatEmoji(0x1F6F7, new String[]{"sled"}, false),
      new GoogleCompatEmoji(0x1F94C, new String[]{"curling_stone"}, false),
      new GoogleCompatEmoji(0x1F3AF, new String[]{"dart"}, false),
      new GoogleCompatEmoji(0x1FA80, new String[]{"yo-yo"}, false),
      new GoogleCompatEmoji(0x1FA81, new String[]{"kite"}, false),
      new GoogleCompatEmoji(0x1F3B1, new String[]{"8ball"}, false),
      new GoogleCompatEmoji(0x1F52E, new String[]{"crystal_ball"}, false),
      new GoogleCompatEmoji(0x1F9FF, new String[]{"nazar_amulet"}, false),
      new GoogleCompatEmoji(0x1F3AE, new String[]{"video_game"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F579, 0xFE0F }, new String[]{"joystick"}, false),
      new GoogleCompatEmoji(0x1F3B0, new String[]{"slot_machine"}, false),
      new GoogleCompatEmoji(0x1F3B2, new String[]{"game_die"}, false),
      new GoogleCompatEmoji(0x1F9E9, new String[]{"jigsaw"}, false),
      new GoogleCompatEmoji(0x1F9F8, new String[]{"teddy_bear"}, false),
      new GoogleCompatEmoji(new int[] { 0x2660, 0xFE0F }, new String[]{"spades"}, false),
      new GoogleCompatEmoji(new int[] { 0x2665, 0xFE0F }, new String[]{"hearts"}, false),
      new GoogleCompatEmoji(new int[] { 0x2666, 0xFE0F }, new String[]{"diamonds"}, false),
      new GoogleCompatEmoji(new int[] { 0x2663, 0xFE0F }, new String[]{"clubs"}, false),
      new GoogleCompatEmoji(new int[] { 0x265F, 0xFE0F }, new String[]{"chess_pawn"}, false),
      new GoogleCompatEmoji(0x1F0CF, new String[]{"black_joker"}, false),
      new GoogleCompatEmoji(0x1F004, new String[]{"mahjong"}, false),
      new GoogleCompatEmoji(0x1F3B4, new String[]{"flower_playing_cards"}, false),
      new GoogleCompatEmoji(0x1F3AD, new String[]{"performing_arts"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5BC, 0xFE0F }, new String[]{"frame_with_picture"}, false),
      new GoogleCompatEmoji(0x1F3A8, new String[]{"art"}, false),
      new GoogleCompatEmoji(0x1F9F5, new String[]{"thread"}, false),
      new GoogleCompatEmoji(0x1F9F6, new String[]{"yarn"}, false)
    };
  }

  private ActivitiesCategoryChunk0() {
    // No instances.
  }
}
