package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class AnimalsAndNatureCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F435, new String[]{"monkey_face"}, false),
      new GoogleCompatEmoji(0x1F412, new String[]{"monkey"}, false),
      new GoogleCompatEmoji(0x1F98D, new String[]{"gorilla"}, false),
      new GoogleCompatEmoji(0x1F9A7, new String[]{"orangutan"}, false),
      new GoogleCompatEmoji(0x1F436, new String[]{"dog"}, false),
      new GoogleCompatEmoji(0x1F415, new String[]{"dog2"}, false),
      new GoogleCompatEmoji(0x1F9AE, new String[]{"guide_dog"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F415, 0x200D, 0x1F9BA }, new String[]{"service_dog"}, false),
      new GoogleCompatEmoji(0x1F429, new String[]{"poodle"}, false),
      new GoogleCompatEmoji(0x1F43A, new String[]{"wolf"}, false),
      new GoogleCompatEmoji(0x1F98A, new String[]{"fox_face"}, false),
      new GoogleCompatEmoji(0x1F99D, new String[]{"raccoon"}, false),
      new GoogleCompatEmoji(0x1F431, new String[]{"cat"}, false),
      new GoogleCompatEmoji(0x1F408, new String[]{"cat2"}, false),
      new GoogleCompatEmoji(0x1F981, new String[]{"lion_face"}, false),
      new GoogleCompatEmoji(0x1F42F, new String[]{"tiger"}, false),
      new GoogleCompatEmoji(0x1F405, new String[]{"tiger2"}, false),
      new GoogleCompatEmoji(0x1F406, new String[]{"leopard"}, false),
      new GoogleCompatEmoji(0x1F434, new String[]{"horse"}, false),
      new GoogleCompatEmoji(0x1F40E, new String[]{"racehorse"}, false),
      new GoogleCompatEmoji(0x1F984, new String[]{"unicorn_face"}, false),
      new GoogleCompatEmoji(0x1F993, new String[]{"zebra_face"}, false),
      new GoogleCompatEmoji(0x1F98C, new String[]{"deer"}, false),
      new GoogleCompatEmoji(0x1F42E, new String[]{"cow"}, false),
      new GoogleCompatEmoji(0x1F402, new String[]{"ox"}, false),
      new GoogleCompatEmoji(0x1F403, new String[]{"water_buffalo"}, false),
      new GoogleCompatEmoji(0x1F404, new String[]{"cow2"}, false),
      new GoogleCompatEmoji(0x1F437, new String[]{"pig"}, false),
      new GoogleCompatEmoji(0x1F416, new String[]{"pig2"}, false),
      new GoogleCompatEmoji(0x1F417, new String[]{"boar"}, false),
      new GoogleCompatEmoji(0x1F43D, new String[]{"pig_nose"}, false),
      new GoogleCompatEmoji(0x1F40F, new String[]{"ram"}, false),
      new GoogleCompatEmoji(0x1F411, new String[]{"sheep"}, false),
      new GoogleCompatEmoji(0x1F410, new String[]{"goat"}, false),
      new GoogleCompatEmoji(0x1F42A, new String[]{"dromedary_camel"}, false),
      new GoogleCompatEmoji(0x1F42B, new String[]{"camel"}, false),
      new GoogleCompatEmoji(0x1F999, new String[]{"llama"}, false),
      new GoogleCompatEmoji(0x1F992, new String[]{"giraffe_face"}, false),
      new GoogleCompatEmoji(0x1F418, new String[]{"elephant"}, false),
      new GoogleCompatEmoji(0x1F98F, new String[]{"rhinoceros"}, false),
      new GoogleCompatEmoji(0x1F99B, new String[]{"hippopotamus"}, false),
      new GoogleCompatEmoji(0x1F42D, new String[]{"mouse"}, false),
      new GoogleCompatEmoji(0x1F401, new String[]{"mouse2"}, false),
      new GoogleCompatEmoji(0x1F400, new String[]{"rat"}, false),
      new GoogleCompatEmoji(0x1F439, new String[]{"hamster"}, false),
      new GoogleCompatEmoji(0x1F430, new String[]{"rabbit"}, false),
      new GoogleCompatEmoji(0x1F407, new String[]{"rabbit2"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F43F, 0xFE0F }, new String[]{"chipmunk"}, false),
      new GoogleCompatEmoji(0x1F994, new String[]{"hedgehog"}, false),
      new GoogleCompatEmoji(0x1F987, new String[]{"bat"}, false),
      new GoogleCompatEmoji(0x1F43B, new String[]{"bear"}, false),
      new GoogleCompatEmoji(0x1F428, new String[]{"koala"}, false),
      new GoogleCompatEmoji(0x1F43C, new String[]{"panda_face"}, false),
      new GoogleCompatEmoji(0x1F9A5, new String[]{"sloth"}, false),
      new GoogleCompatEmoji(0x1F9A6, new String[]{"otter"}, false),
      new GoogleCompatEmoji(0x1F9A8, new String[]{"skunk"}, false),
      new GoogleCompatEmoji(0x1F998, new String[]{"kangaroo"}, false),
      new GoogleCompatEmoji(0x1F9A1, new String[]{"badger"}, false),
      new GoogleCompatEmoji(0x1F43E, new String[]{"feet", "paw_prints"}, false),
      new GoogleCompatEmoji(0x1F983, new String[]{"turkey"}, false),
      new GoogleCompatEmoji(0x1F414, new String[]{"chicken"}, false),
      new GoogleCompatEmoji(0x1F413, new String[]{"rooster"}, false),
      new GoogleCompatEmoji(0x1F423, new String[]{"hatching_chick"}, false),
      new GoogleCompatEmoji(0x1F424, new String[]{"baby_chick"}, false),
      new GoogleCompatEmoji(0x1F425, new String[]{"hatched_chick"}, false),
      new GoogleCompatEmoji(0x1F426, new String[]{"bird"}, false),
      new GoogleCompatEmoji(0x1F427, new String[]{"penguin"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F54A, 0xFE0F }, new String[]{"dove_of_peace"}, false),
      new GoogleCompatEmoji(0x1F985, new String[]{"eagle"}, false),
      new GoogleCompatEmoji(0x1F986, new String[]{"duck"}, false),
      new GoogleCompatEmoji(0x1F9A2, new String[]{"swan"}, false),
      new GoogleCompatEmoji(0x1F989, new String[]{"owl"}, false),
      new GoogleCompatEmoji(0x1F9A9, new String[]{"flamingo"}, false),
      new GoogleCompatEmoji(0x1F99A, new String[]{"peacock"}, false),
      new GoogleCompatEmoji(0x1F99C, new String[]{"parrot"}, false),
      new GoogleCompatEmoji(0x1F438, new String[]{"frog"}, false),
      new GoogleCompatEmoji(0x1F40A, new String[]{"crocodile"}, false),
      new GoogleCompatEmoji(0x1F422, new String[]{"turtle"}, false),
      new GoogleCompatEmoji(0x1F98E, new String[]{"lizard"}, false),
      new GoogleCompatEmoji(0x1F40D, new String[]{"snake"}, false),
      new GoogleCompatEmoji(0x1F432, new String[]{"dragon_face"}, false),
      new GoogleCompatEmoji(0x1F409, new String[]{"dragon"}, false),
      new GoogleCompatEmoji(0x1F995, new String[]{"sauropod"}, false),
      new GoogleCompatEmoji(0x1F996, new String[]{"t-rex"}, false),
      new GoogleCompatEmoji(0x1F433, new String[]{"whale"}, false),
      new GoogleCompatEmoji(0x1F40B, new String[]{"whale2"}, false),
      new GoogleCompatEmoji(0x1F42C, new String[]{"dolphin", "flipper"}, false),
      new GoogleCompatEmoji(0x1F41F, new String[]{"fish"}, false),
      new GoogleCompatEmoji(0x1F420, new String[]{"tropical_fish"}, false),
      new GoogleCompatEmoji(0x1F421, new String[]{"blowfish"}, false),
      new GoogleCompatEmoji(0x1F988, new String[]{"shark"}, false),
      new GoogleCompatEmoji(0x1F419, new String[]{"octopus"}, false),
      new GoogleCompatEmoji(0x1F41A, new String[]{"shell"}, false),
      new GoogleCompatEmoji(0x1F40C, new String[]{"snail"}, false),
      new GoogleCompatEmoji(0x1F98B, new String[]{"butterfly"}, false),
      new GoogleCompatEmoji(0x1F41B, new String[]{"bug"}, false),
      new GoogleCompatEmoji(0x1F41C, new String[]{"ant"}, false),
      new GoogleCompatEmoji(0x1F41D, new String[]{"bee", "honeybee"}, false),
      new GoogleCompatEmoji(0x1F41E, new String[]{"beetle"}, false),
      new GoogleCompatEmoji(0x1F997, new String[]{"cricket"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F577, 0xFE0F }, new String[]{"spider"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F578, 0xFE0F }, new String[]{"spider_web"}, false),
      new GoogleCompatEmoji(0x1F982, new String[]{"scorpion"}, false),
      new GoogleCompatEmoji(0x1F99F, new String[]{"mosquito"}, false),
      new GoogleCompatEmoji(0x1F9A0, new String[]{"microbe"}, false),
      new GoogleCompatEmoji(0x1F490, new String[]{"bouquet"}, false),
      new GoogleCompatEmoji(0x1F338, new String[]{"cherry_blossom"}, false),
      new GoogleCompatEmoji(0x1F4AE, new String[]{"white_flower"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3F5, 0xFE0F }, new String[]{"rosette"}, false),
      new GoogleCompatEmoji(0x1F339, new String[]{"rose"}, false),
      new GoogleCompatEmoji(0x1F940, new String[]{"wilted_flower"}, false),
      new GoogleCompatEmoji(0x1F33A, new String[]{"hibiscus"}, false),
      new GoogleCompatEmoji(0x1F33B, new String[]{"sunflower"}, false),
      new GoogleCompatEmoji(0x1F33C, new String[]{"blossom"}, false),
      new GoogleCompatEmoji(0x1F337, new String[]{"tulip"}, false),
      new GoogleCompatEmoji(0x1F331, new String[]{"seedling"}, false),
      new GoogleCompatEmoji(0x1F332, new String[]{"evergreen_tree"}, false),
      new GoogleCompatEmoji(0x1F333, new String[]{"deciduous_tree"}, false),
      new GoogleCompatEmoji(0x1F334, new String[]{"palm_tree"}, false),
      new GoogleCompatEmoji(0x1F335, new String[]{"cactus"}, false),
      new GoogleCompatEmoji(0x1F33E, new String[]{"ear_of_rice"}, false),
      new GoogleCompatEmoji(0x1F33F, new String[]{"herb"}, false),
      new GoogleCompatEmoji(new int[] { 0x2618, 0xFE0F }, new String[]{"shamrock"}, false),
      new GoogleCompatEmoji(0x1F340, new String[]{"four_leaf_clover"}, false),
      new GoogleCompatEmoji(0x1F341, new String[]{"maple_leaf"}, false),
      new GoogleCompatEmoji(0x1F342, new String[]{"fallen_leaf"}, false),
      new GoogleCompatEmoji(0x1F343, new String[]{"leaves"}, false)
    };
  }

  private AnimalsAndNatureCategoryChunk0() {
    // No instances.
  }
}
