package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class AnimalsAndNatureCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F435, false),
      new GoogleCompatEmoji(0x1F412, false),
      new GoogleCompatEmoji(0x1F98D, false),
      new GoogleCompatEmoji(0x1F9A7, false),
      new GoogleCompatEmoji(0x1F436, false),
      new GoogleCompatEmoji(0x1F415, false),
      new GoogleCompatEmoji(0x1F9AE, false),
      new GoogleCompatEmoji(new int[] { 0x1F415, 0x200D, 0x1F9BA }, false),
      new GoogleCompatEmoji(0x1F429, false),
      new GoogleCompatEmoji(0x1F43A, false),
      new GoogleCompatEmoji(0x1F98A, false),
      new GoogleCompatEmoji(0x1F99D, false),
      new GoogleCompatEmoji(0x1F431, false),
      new GoogleCompatEmoji(0x1F408, false),
      new GoogleCompatEmoji(0x1F981, false),
      new GoogleCompatEmoji(0x1F42F, false),
      new GoogleCompatEmoji(0x1F405, false),
      new GoogleCompatEmoji(0x1F406, false),
      new GoogleCompatEmoji(0x1F434, false),
      new GoogleCompatEmoji(0x1F40E, false),
      new GoogleCompatEmoji(0x1F984, false),
      new GoogleCompatEmoji(0x1F993, false),
      new GoogleCompatEmoji(0x1F98C, false),
      new GoogleCompatEmoji(0x1F42E, false),
      new GoogleCompatEmoji(0x1F402, false),
      new GoogleCompatEmoji(0x1F403, false),
      new GoogleCompatEmoji(0x1F404, false),
      new GoogleCompatEmoji(0x1F437, false),
      new GoogleCompatEmoji(0x1F416, false),
      new GoogleCompatEmoji(0x1F417, false),
      new GoogleCompatEmoji(0x1F43D, false),
      new GoogleCompatEmoji(0x1F40F, false),
      new GoogleCompatEmoji(0x1F411, false),
      new GoogleCompatEmoji(0x1F410, false),
      new GoogleCompatEmoji(0x1F42A, false),
      new GoogleCompatEmoji(0x1F42B, false),
      new GoogleCompatEmoji(0x1F999, false),
      new GoogleCompatEmoji(0x1F992, false),
      new GoogleCompatEmoji(0x1F418, false),
      new GoogleCompatEmoji(0x1F98F, false),
      new GoogleCompatEmoji(0x1F99B, false),
      new GoogleCompatEmoji(0x1F42D, false),
      new GoogleCompatEmoji(0x1F401, false),
      new GoogleCompatEmoji(0x1F400, false),
      new GoogleCompatEmoji(0x1F439, false),
      new GoogleCompatEmoji(0x1F430, false),
      new GoogleCompatEmoji(0x1F407, false),
      new GoogleCompatEmoji(new int[] { 0x1F43F, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F994, false),
      new GoogleCompatEmoji(0x1F987, false),
      new GoogleCompatEmoji(0x1F43B, false),
      new GoogleCompatEmoji(0x1F428, false),
      new GoogleCompatEmoji(0x1F43C, false),
      new GoogleCompatEmoji(0x1F9A5, false),
      new GoogleCompatEmoji(0x1F9A6, false),
      new GoogleCompatEmoji(0x1F9A8, false),
      new GoogleCompatEmoji(0x1F998, false),
      new GoogleCompatEmoji(0x1F9A1, false),
      new GoogleCompatEmoji(0x1F43E, false),
      new GoogleCompatEmoji(0x1F983, false),
      new GoogleCompatEmoji(0x1F414, false),
      new GoogleCompatEmoji(0x1F413, false),
      new GoogleCompatEmoji(0x1F423, false),
      new GoogleCompatEmoji(0x1F424, false),
      new GoogleCompatEmoji(0x1F425, false),
      new GoogleCompatEmoji(0x1F426, false),
      new GoogleCompatEmoji(0x1F427, false),
      new GoogleCompatEmoji(new int[] { 0x1F54A, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F985, false),
      new GoogleCompatEmoji(0x1F986, false),
      new GoogleCompatEmoji(0x1F9A2, false),
      new GoogleCompatEmoji(0x1F989, false),
      new GoogleCompatEmoji(0x1F9A9, false),
      new GoogleCompatEmoji(0x1F99A, false),
      new GoogleCompatEmoji(0x1F99C, false),
      new GoogleCompatEmoji(0x1F438, false),
      new GoogleCompatEmoji(0x1F40A, false),
      new GoogleCompatEmoji(0x1F422, false),
      new GoogleCompatEmoji(0x1F98E, false),
      new GoogleCompatEmoji(0x1F40D, false),
      new GoogleCompatEmoji(0x1F432, false),
      new GoogleCompatEmoji(0x1F409, false),
      new GoogleCompatEmoji(0x1F995, false),
      new GoogleCompatEmoji(0x1F996, false),
      new GoogleCompatEmoji(0x1F433, false),
      new GoogleCompatEmoji(0x1F40B, false),
      new GoogleCompatEmoji(0x1F42C, false),
      new GoogleCompatEmoji(0x1F41F, false),
      new GoogleCompatEmoji(0x1F420, false),
      new GoogleCompatEmoji(0x1F421, false),
      new GoogleCompatEmoji(0x1F988, false),
      new GoogleCompatEmoji(0x1F419, false),
      new GoogleCompatEmoji(0x1F41A, false),
      new GoogleCompatEmoji(0x1F40C, false),
      new GoogleCompatEmoji(0x1F98B, false),
      new GoogleCompatEmoji(0x1F41B, false),
      new GoogleCompatEmoji(0x1F41C, false),
      new GoogleCompatEmoji(0x1F41D, false),
      new GoogleCompatEmoji(0x1F41E, false),
      new GoogleCompatEmoji(0x1F997, false),
      new GoogleCompatEmoji(new int[] { 0x1F577, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F578, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F982, false),
      new GoogleCompatEmoji(0x1F99F, false),
      new GoogleCompatEmoji(0x1F9A0, false),
      new GoogleCompatEmoji(0x1F490, false),
      new GoogleCompatEmoji(0x1F338, false),
      new GoogleCompatEmoji(0x1F4AE, false),
      new GoogleCompatEmoji(new int[] { 0x1F3F5, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F339, false),
      new GoogleCompatEmoji(0x1F940, false),
      new GoogleCompatEmoji(0x1F33A, false),
      new GoogleCompatEmoji(0x1F33B, false),
      new GoogleCompatEmoji(0x1F33C, false),
      new GoogleCompatEmoji(0x1F337, false),
      new GoogleCompatEmoji(0x1F331, false),
      new GoogleCompatEmoji(0x1F332, false),
      new GoogleCompatEmoji(0x1F333, false),
      new GoogleCompatEmoji(0x1F334, false),
      new GoogleCompatEmoji(0x1F335, false),
      new GoogleCompatEmoji(0x1F33E, false),
      new GoogleCompatEmoji(0x1F33F, false),
      new GoogleCompatEmoji(new int[] { 0x2618, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F340, false),
      new GoogleCompatEmoji(0x1F341, false),
      new GoogleCompatEmoji(0x1F342, false),
      new GoogleCompatEmoji(0x1F343, false)
    };
  }

  private AnimalsAndNatureCategoryChunk0() {
    // No instances.
  }
}
