/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class FlagsCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F3C1, new String[]{"checkered_flag"}, false),
      new GoogleCompatEmoji(0x1F6A9, new String[]{"triangular_flag_on_post"}, false),
      new GoogleCompatEmoji(0x1F38C, new String[]{"crossed_flags"}, false),
      new GoogleCompatEmoji(0x1F3F4, new String[]{"waving_black_flag"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3F3, 0xFE0F }, new String[]{"waving_white_flag"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3F3, 0xFE0F, 0x200D, 0x1F308 }, new String[]{"rainbow-flag"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3F4, 0x200D, 0x2620, 0xFE0F }, new String[]{"pirate_flag"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1E8 }, new String[]{"flag-ac"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1E9 }, new String[]{"flag-ad"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1EA }, new String[]{"flag-ae"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1EB }, new String[]{"flag-af"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1EC }, new String[]{"flag-ag"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1EE }, new String[]{"flag-ai"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1F1 }, new String[]{"flag-al"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1F2 }, new String[]{"flag-am"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1F4 }, new String[]{"flag-ao"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1F6 }, new String[]{"flag-aq"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1F7 }, new String[]{"flag-ar"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1F8 }, new String[]{"flag-as"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1F9 }, new String[]{"flag-at"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1FA }, new String[]{"flag-au"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1FC }, new String[]{"flag-aw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1FD }, new String[]{"flag-ax"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E6, 0x1F1FF }, new String[]{"flag-az"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1E6 }, new String[]{"flag-ba"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1E7 }, new String[]{"flag-bb"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1E9 }, new String[]{"flag-bd"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1EA }, new String[]{"flag-be"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1EB }, new String[]{"flag-bf"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1EC }, new String[]{"flag-bg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1ED }, new String[]{"flag-bh"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1EE }, new String[]{"flag-bi"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1EF }, new String[]{"flag-bj"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F1 }, new String[]{"flag-bl"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F2 }, new String[]{"flag-bm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F3 }, new String[]{"flag-bn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F4 }, new String[]{"flag-bo"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F6 }, new String[]{"flag-bq"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F7 }, new String[]{"flag-br"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F8 }, new String[]{"flag-bs"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1F9 }, new String[]{"flag-bt"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1FB }, new String[]{"flag-bv"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1FC }, new String[]{"flag-bw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1FE }, new String[]{"flag-by"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E7, 0x1F1FF }, new String[]{"flag-bz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1E6 }, new String[]{"flag-ca"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1E8 }, new String[]{"flag-cc"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1E9 }, new String[]{"flag-cd"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1EB }, new String[]{"flag-cf"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1EC }, new String[]{"flag-cg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1ED }, new String[]{"flag-ch"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1EE }, new String[]{"flag-ci"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1F0 }, new String[]{"flag-ck"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1F1 }, new String[]{"flag-cl"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1F2 }, new String[]{"flag-cm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1F3 }, new String[]{"cn", "flag-cn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1F4 }, new String[]{"flag-co"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1F5 }, new String[]{"flag-cp"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1F7 }, new String[]{"flag-cr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1FA }, new String[]{"flag-cu"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1FB }, new String[]{"flag-cv"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1FC }, new String[]{"flag-cw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1FD }, new String[]{"flag-cx"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1FE }, new String[]{"flag-cy"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E8, 0x1F1FF }, new String[]{"flag-cz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E9, 0x1F1EA }, new String[]{"de", "flag-de"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E9, 0x1F1EC }, new String[]{"flag-dg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E9, 0x1F1EF }, new String[]{"flag-dj"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E9, 0x1F1F0 }, new String[]{"flag-dk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E9, 0x1F1F2 }, new String[]{"flag-dm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E9, 0x1F1F4 }, new String[]{"flag-do"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1E9, 0x1F1FF }, new String[]{"flag-dz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1E6 }, new String[]{"flag-ea"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1E8 }, new String[]{"flag-ec"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1EA }, new String[]{"flag-ee"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1EC }, new String[]{"flag-eg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1ED }, new String[]{"flag-eh"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1F7 }, new String[]{"flag-er"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1F8 }, new String[]{"es", "flag-es"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1F9 }, new String[]{"flag-et"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EA, 0x1F1FA }, new String[]{"flag-eu"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EB, 0x1F1EE }, new String[]{"flag-fi"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EB, 0x1F1EF }, new String[]{"flag-fj"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EB, 0x1F1F0 }, new String[]{"flag-fk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EB, 0x1F1F2 }, new String[]{"flag-fm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EB, 0x1F1F4 }, new String[]{"flag-fo"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EB, 0x1F1F7 }, new String[]{"fr", "flag-fr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1E6 }, new String[]{"flag-ga"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1E7 }, new String[]{"gb", "uk", "flag-gb"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1E9 }, new String[]{"flag-gd"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1EA }, new String[]{"flag-ge"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1EB }, new String[]{"flag-gf"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1EC }, new String[]{"flag-gg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1ED }, new String[]{"flag-gh"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1EE }, new String[]{"flag-gi"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F1 }, new String[]{"flag-gl"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F2 }, new String[]{"flag-gm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F3 }, new String[]{"flag-gn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F5 }, new String[]{"flag-gp"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F6 }, new String[]{"flag-gq"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F7 }, new String[]{"flag-gr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F8 }, new String[]{"flag-gs"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1F9 }, new String[]{"flag-gt"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1FA }, new String[]{"flag-gu"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1FC }, new String[]{"flag-gw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EC, 0x1F1FE }, new String[]{"flag-gy"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1ED, 0x1F1F0 }, new String[]{"flag-hk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1ED, 0x1F1F2 }, new String[]{"flag-hm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1ED, 0x1F1F3 }, new String[]{"flag-hn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1ED, 0x1F1F7 }, new String[]{"flag-hr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1ED, 0x1F1F9 }, new String[]{"flag-ht"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1ED, 0x1F1FA }, new String[]{"flag-hu"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1E8 }, new String[]{"flag-ic"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1E9 }, new String[]{"flag-id"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1EA }, new String[]{"flag-ie"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F1 }, new String[]{"flag-il"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F2 }, new String[]{"flag-im"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F3 }, new String[]{"flag-in"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F4 }, new String[]{"flag-io"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F6 }, new String[]{"flag-iq"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F7 }, new String[]{"flag-ir"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F8 }, new String[]{"flag-is"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EE, 0x1F1F9 }, new String[]{"it", "flag-it"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EF, 0x1F1EA }, new String[]{"flag-je"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EF, 0x1F1F2 }, new String[]{"flag-jm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EF, 0x1F1F4 }, new String[]{"flag-jo"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1EF, 0x1F1F5 }, new String[]{"jp", "flag-jp"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1EA }, new String[]{"flag-ke"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1EC }, new String[]{"flag-kg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1ED }, new String[]{"flag-kh"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1EE }, new String[]{"flag-ki"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1F2 }, new String[]{"flag-km"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1F3 }, new String[]{"flag-kn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1F5 }, new String[]{"flag-kp"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1F7 }, new String[]{"kr", "flag-kr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1FC }, new String[]{"flag-kw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1FE }, new String[]{"flag-ky"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F0, 0x1F1FF }, new String[]{"flag-kz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1E6 }, new String[]{"flag-la"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1E7 }, new String[]{"flag-lb"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1E8 }, new String[]{"flag-lc"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1EE }, new String[]{"flag-li"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1F0 }, new String[]{"flag-lk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1F7 }, new String[]{"flag-lr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1F8 }, new String[]{"flag-ls"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1F9 }, new String[]{"flag-lt"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1FA }, new String[]{"flag-lu"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1FB }, new String[]{"flag-lv"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F1, 0x1F1FE }, new String[]{"flag-ly"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1E6 }, new String[]{"flag-ma"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1E8 }, new String[]{"flag-mc"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1E9 }, new String[]{"flag-md"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1EA }, new String[]{"flag-me"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1EB }, new String[]{"flag-mf"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1EC }, new String[]{"flag-mg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1ED }, new String[]{"flag-mh"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F0 }, new String[]{"flag-mk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F1 }, new String[]{"flag-ml"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F2 }, new String[]{"flag-mm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F3 }, new String[]{"flag-mn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F4 }, new String[]{"flag-mo"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F5 }, new String[]{"flag-mp"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F6 }, new String[]{"flag-mq"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F7 }, new String[]{"flag-mr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F8 }, new String[]{"flag-ms"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1F9 }, new String[]{"flag-mt"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1FA }, new String[]{"flag-mu"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1FB }, new String[]{"flag-mv"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1FC }, new String[]{"flag-mw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1FD }, new String[]{"flag-mx"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1FE }, new String[]{"flag-my"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F2, 0x1F1FF }, new String[]{"flag-mz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1E6 }, new String[]{"flag-na"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1E8 }, new String[]{"flag-nc"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1EA }, new String[]{"flag-ne"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1EB }, new String[]{"flag-nf"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1EC }, new String[]{"flag-ng"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1EE }, new String[]{"flag-ni"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1F1 }, new String[]{"flag-nl"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1F4 }, new String[]{"flag-no"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1F5 }, new String[]{"flag-np"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1F7 }, new String[]{"flag-nr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1FA }, new String[]{"flag-nu"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F3, 0x1F1FF }, new String[]{"flag-nz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F4, 0x1F1F2 }, new String[]{"flag-om"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1E6 }, new String[]{"flag-pa"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1EA }, new String[]{"flag-pe"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1EB }, new String[]{"flag-pf"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1EC }, new String[]{"flag-pg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1ED }, new String[]{"flag-ph"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1F0 }, new String[]{"flag-pk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1F1 }, new String[]{"flag-pl"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1F2 }, new String[]{"flag-pm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1F3 }, new String[]{"flag-pn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1F7 }, new String[]{"flag-pr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1F8 }, new String[]{"flag-ps"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1F9 }, new String[]{"flag-pt"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1FC }, new String[]{"flag-pw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F5, 0x1F1FE }, new String[]{"flag-py"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F6, 0x1F1E6 }, new String[]{"flag-qa"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F7, 0x1F1EA }, new String[]{"flag-re"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F7, 0x1F1F4 }, new String[]{"flag-ro"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F7, 0x1F1F8 }, new String[]{"flag-rs"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F7, 0x1F1FA }, new String[]{"ru", "flag-ru"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F7, 0x1F1FC }, new String[]{"flag-rw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1E6 }, new String[]{"flag-sa"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1E7 }, new String[]{"flag-sb"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1E8 }, new String[]{"flag-sc"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1E9 }, new String[]{"flag-sd"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1EA }, new String[]{"flag-se"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1EC }, new String[]{"flag-sg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1ED }, new String[]{"flag-sh"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1EE }, new String[]{"flag-si"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1EF }, new String[]{"flag-sj"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F0 }, new String[]{"flag-sk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F1 }, new String[]{"flag-sl"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F2 }, new String[]{"flag-sm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F3 }, new String[]{"flag-sn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F4 }, new String[]{"flag-so"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F7 }, new String[]{"flag-sr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F8 }, new String[]{"flag-ss"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1F9 }, new String[]{"flag-st"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1FB }, new String[]{"flag-sv"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1FD }, new String[]{"flag-sx"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1FE }, new String[]{"flag-sy"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F8, 0x1F1FF }, new String[]{"flag-sz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1E6 }, new String[]{"flag-ta"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1E8 }, new String[]{"flag-tc"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1E9 }, new String[]{"flag-td"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1EB }, new String[]{"flag-tf"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1EC }, new String[]{"flag-tg"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1ED }, new String[]{"flag-th"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1EF }, new String[]{"flag-tj"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1F0 }, new String[]{"flag-tk"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1F1 }, new String[]{"flag-tl"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1F2 }, new String[]{"flag-tm"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1F3 }, new String[]{"flag-tn"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1F4 }, new String[]{"flag-to"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1F7 }, new String[]{"flag-tr"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1F9 }, new String[]{"flag-tt"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1FB }, new String[]{"flag-tv"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1FC }, new String[]{"flag-tw"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1F9, 0x1F1FF }, new String[]{"flag-tz"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1FA, 0x1F1E6 }, new String[]{"flag-ua"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1FA, 0x1F1EC }, new String[]{"flag-ug"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1FA, 0x1F1F2 }, new String[]{"flag-um"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1FA, 0x1F1F3 }, new String[]{"flag-un"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1FA, 0x1F1F8 }, new String[]{"us", "flag-us"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1FA, 0x1F1FE }, new String[]{"flag-uy"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F1FA, 0x1F1FF }, new String[]{"flag-uz"}, false)
    };
  }

  private FlagsCategoryChunk0() {
    // No instances.
  }
}
