package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class FoodAndDrinkCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F347, false),
      new GoogleCompatEmoji(0x1F348, false),
      new GoogleCompatEmoji(0x1F349, false),
      new GoogleCompatEmoji(0x1F34A, false),
      new GoogleCompatEmoji(0x1F34B, false),
      new GoogleCompatEmoji(0x1F34C, false),
      new GoogleCompatEmoji(0x1F34D, false),
      new GoogleCompatEmoji(0x1F96D, false),
      new GoogleCompatEmoji(0x1F34E, false),
      new GoogleCompatEmoji(0x1F34F, false),
      new GoogleCompatEmoji(0x1F350, false),
      new GoogleCompatEmoji(0x1F351, false),
      new GoogleCompatEmoji(0x1F352, false),
      new GoogleCompatEmoji(0x1F353, false),
      new GoogleCompatEmoji(0x1F95D, false),
      new GoogleCompatEmoji(0x1F345, false),
      new GoogleCompatEmoji(0x1F965, false),
      new GoogleCompatEmoji(0x1F951, false),
      new GoogleCompatEmoji(0x1F346, false),
      new GoogleCompatEmoji(0x1F954, false),
      new GoogleCompatEmoji(0x1F955, false),
      new GoogleCompatEmoji(0x1F33D, false),
      new GoogleCompatEmoji(new int[] { 0x1F336, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F952, false),
      new GoogleCompatEmoji(0x1F96C, false),
      new GoogleCompatEmoji(0x1F966, false),
      new GoogleCompatEmoji(0x1F9C4, false),
      new GoogleCompatEmoji(0x1F9C5, false),
      new GoogleCompatEmoji(0x1F344, false),
      new GoogleCompatEmoji(0x1F95C, false),
      new GoogleCompatEmoji(0x1F330, false),
      new GoogleCompatEmoji(0x1F35E, false),
      new GoogleCompatEmoji(0x1F950, false),
      new GoogleCompatEmoji(0x1F956, false),
      new GoogleCompatEmoji(0x1F968, false),
      new GoogleCompatEmoji(0x1F96F, false),
      new GoogleCompatEmoji(0x1F95E, false),
      new GoogleCompatEmoji(0x1F9C7, false),
      new GoogleCompatEmoji(0x1F9C0, false),
      new GoogleCompatEmoji(0x1F356, false),
      new GoogleCompatEmoji(0x1F357, false),
      new GoogleCompatEmoji(0x1F969, false),
      new GoogleCompatEmoji(0x1F953, false),
      new GoogleCompatEmoji(0x1F354, false),
      new GoogleCompatEmoji(0x1F35F, false),
      new GoogleCompatEmoji(0x1F355, false),
      new GoogleCompatEmoji(0x1F32D, false),
      new GoogleCompatEmoji(0x1F96A, false),
      new GoogleCompatEmoji(0x1F32E, false),
      new GoogleCompatEmoji(0x1F32F, false),
      new GoogleCompatEmoji(0x1F959, false),
      new GoogleCompatEmoji(0x1F9C6, false),
      new GoogleCompatEmoji(0x1F95A, false),
      new GoogleCompatEmoji(0x1F373, false),
      new GoogleCompatEmoji(0x1F958, false),
      new GoogleCompatEmoji(0x1F372, false),
      new GoogleCompatEmoji(0x1F963, false),
      new GoogleCompatEmoji(0x1F957, false),
      new GoogleCompatEmoji(0x1F37F, false),
      new GoogleCompatEmoji(0x1F9C8, false),
      new GoogleCompatEmoji(0x1F9C2, false),
      new GoogleCompatEmoji(0x1F96B, false),
      new GoogleCompatEmoji(0x1F371, false),
      new GoogleCompatEmoji(0x1F358, false),
      new GoogleCompatEmoji(0x1F359, false),
      new GoogleCompatEmoji(0x1F35A, false),
      new GoogleCompatEmoji(0x1F35B, false),
      new GoogleCompatEmoji(0x1F35C, false),
      new GoogleCompatEmoji(0x1F35D, false),
      new GoogleCompatEmoji(0x1F360, false),
      new GoogleCompatEmoji(0x1F362, false),
      new GoogleCompatEmoji(0x1F363, false),
      new GoogleCompatEmoji(0x1F364, false),
      new GoogleCompatEmoji(0x1F365, false),
      new GoogleCompatEmoji(0x1F96E, false),
      new GoogleCompatEmoji(0x1F361, false),
      new GoogleCompatEmoji(0x1F95F, false),
      new GoogleCompatEmoji(0x1F960, false),
      new GoogleCompatEmoji(0x1F961, false),
      new GoogleCompatEmoji(0x1F980, false),
      new GoogleCompatEmoji(0x1F99E, false),
      new GoogleCompatEmoji(0x1F990, false),
      new GoogleCompatEmoji(0x1F991, false),
      new GoogleCompatEmoji(0x1F9AA, false),
      new GoogleCompatEmoji(0x1F366, false),
      new GoogleCompatEmoji(0x1F367, false),
      new GoogleCompatEmoji(0x1F368, false),
      new GoogleCompatEmoji(0x1F369, false),
      new GoogleCompatEmoji(0x1F36A, false),
      new GoogleCompatEmoji(0x1F382, false),
      new GoogleCompatEmoji(0x1F370, false),
      new GoogleCompatEmoji(0x1F9C1, false),
      new GoogleCompatEmoji(0x1F967, false),
      new GoogleCompatEmoji(0x1F36B, false),
      new GoogleCompatEmoji(0x1F36C, false),
      new GoogleCompatEmoji(0x1F36D, false),
      new GoogleCompatEmoji(0x1F36E, false),
      new GoogleCompatEmoji(0x1F36F, false),
      new GoogleCompatEmoji(0x1F37C, false),
      new GoogleCompatEmoji(0x1F95B, false),
      new GoogleCompatEmoji(0x2615, false),
      new GoogleCompatEmoji(0x1F375, false),
      new GoogleCompatEmoji(0x1F376, false),
      new GoogleCompatEmoji(0x1F37E, false),
      new GoogleCompatEmoji(0x1F377, false),
      new GoogleCompatEmoji(0x1F378, false),
      new GoogleCompatEmoji(0x1F379, false),
      new GoogleCompatEmoji(0x1F37A, false),
      new GoogleCompatEmoji(0x1F37B, false),
      new GoogleCompatEmoji(0x1F942, false),
      new GoogleCompatEmoji(0x1F943, false),
      new GoogleCompatEmoji(0x1F964, false),
      new GoogleCompatEmoji(0x1F9C3, false),
      new GoogleCompatEmoji(0x1F9C9, false),
      new GoogleCompatEmoji(0x1F9CA, false),
      new GoogleCompatEmoji(0x1F962, false),
      new GoogleCompatEmoji(new int[] { 0x1F37D, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F374, false),
      new GoogleCompatEmoji(0x1F944, false),
      new GoogleCompatEmoji(0x1F52A, false),
      new GoogleCompatEmoji(0x1F3FA, false)
    };
  }

  private FoodAndDrinkCategoryChunk0() {
    // No instances.
  }
}
