package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class ObjectsCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F453, false),
      new GoogleCompatEmoji(new int[] { 0x1F576, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F97D, false),
      new GoogleCompatEmoji(0x1F97C, false),
      new GoogleCompatEmoji(0x1F9BA, false),
      new GoogleCompatEmoji(0x1F454, false),
      new GoogleCompatEmoji(0x1F455, false),
      new GoogleCompatEmoji(0x1F456, false),
      new GoogleCompatEmoji(0x1F9E3, false),
      new GoogleCompatEmoji(0x1F9E4, false),
      new GoogleCompatEmoji(0x1F9E5, false),
      new GoogleCompatEmoji(0x1F9E6, false),
      new GoogleCompatEmoji(0x1F457, false),
      new GoogleCompatEmoji(0x1F458, false),
      new GoogleCompatEmoji(0x1F97B, false),
      new GoogleCompatEmoji(0x1FA71, false),
      new GoogleCompatEmoji(0x1FA72, false),
      new GoogleCompatEmoji(0x1FA73, false),
      new GoogleCompatEmoji(0x1F459, false),
      new GoogleCompatEmoji(0x1F45A, false),
      new GoogleCompatEmoji(0x1F45B, false),
      new GoogleCompatEmoji(0x1F45C, false),
      new GoogleCompatEmoji(0x1F45D, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CD, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F392, false),
      new GoogleCompatEmoji(0x1F45E, false),
      new GoogleCompatEmoji(0x1F45F, false),
      new GoogleCompatEmoji(0x1F97E, false),
      new GoogleCompatEmoji(0x1F97F, false),
      new GoogleCompatEmoji(0x1F460, false),
      new GoogleCompatEmoji(0x1F461, false),
      new GoogleCompatEmoji(0x1FA70, false),
      new GoogleCompatEmoji(0x1F462, false),
      new GoogleCompatEmoji(0x1F451, false),
      new GoogleCompatEmoji(0x1F452, false),
      new GoogleCompatEmoji(0x1F3A9, false),
      new GoogleCompatEmoji(0x1F393, false),
      new GoogleCompatEmoji(0x1F9E2, false),
      new GoogleCompatEmoji(new int[] { 0x26D1, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4FF, false),
      new GoogleCompatEmoji(0x1F484, false),
      new GoogleCompatEmoji(0x1F48D, false),
      new GoogleCompatEmoji(0x1F48E, false),
      new GoogleCompatEmoji(0x1F507, false),
      new GoogleCompatEmoji(0x1F508, false),
      new GoogleCompatEmoji(0x1F509, false),
      new GoogleCompatEmoji(0x1F50A, false),
      new GoogleCompatEmoji(0x1F4E2, false),
      new GoogleCompatEmoji(0x1F4E3, false),
      new GoogleCompatEmoji(0x1F4EF, false),
      new GoogleCompatEmoji(0x1F514, false),
      new GoogleCompatEmoji(0x1F515, false),
      new GoogleCompatEmoji(0x1F3BC, false),
      new GoogleCompatEmoji(0x1F3B5, false),
      new GoogleCompatEmoji(0x1F3B6, false),
      new GoogleCompatEmoji(new int[] { 0x1F399, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F39A, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F39B, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3A4, false),
      new GoogleCompatEmoji(0x1F3A7, false),
      new GoogleCompatEmoji(0x1F4FB, false),
      new GoogleCompatEmoji(0x1F3B7, false),
      new GoogleCompatEmoji(0x1F3B8, false),
      new GoogleCompatEmoji(0x1F3B9, false),
      new GoogleCompatEmoji(0x1F3BA, false),
      new GoogleCompatEmoji(0x1F3BB, false),
      new GoogleCompatEmoji(0x1FA95, false),
      new GoogleCompatEmoji(0x1F941, false),
      new GoogleCompatEmoji(0x1F4F1, false),
      new GoogleCompatEmoji(0x1F4F2, false),
      new GoogleCompatEmoji(new int[] { 0x260E, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4DE, false),
      new GoogleCompatEmoji(0x1F4DF, false),
      new GoogleCompatEmoji(0x1F4E0, false),
      new GoogleCompatEmoji(0x1F50B, false),
      new GoogleCompatEmoji(0x1F50C, false),
      new GoogleCompatEmoji(0x1F4BB, false),
      new GoogleCompatEmoji(new int[] { 0x1F5A5, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5A8, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2328, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5B1, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5B2, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4BD, false),
      new GoogleCompatEmoji(0x1F4BE, false),
      new GoogleCompatEmoji(0x1F4BF, false),
      new GoogleCompatEmoji(0x1F4C0, false),
      new GoogleCompatEmoji(0x1F9EE, false),
      new GoogleCompatEmoji(0x1F3A5, false),
      new GoogleCompatEmoji(new int[] { 0x1F39E, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F4FD, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3AC, false),
      new GoogleCompatEmoji(0x1F4FA, false),
      new GoogleCompatEmoji(0x1F4F7, false),
      new GoogleCompatEmoji(0x1F4F8, false),
      new GoogleCompatEmoji(0x1F4F9, false),
      new GoogleCompatEmoji(0x1F4FC, false),
      new GoogleCompatEmoji(0x1F50D, false),
      new GoogleCompatEmoji(0x1F50E, false),
      new GoogleCompatEmoji(new int[] { 0x1F56F, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4A1, false),
      new GoogleCompatEmoji(0x1F526, false),
      new GoogleCompatEmoji(0x1F3EE, false),
      new GoogleCompatEmoji(0x1FA94, false),
      new GoogleCompatEmoji(0x1F4D4, false),
      new GoogleCompatEmoji(0x1F4D5, false),
      new GoogleCompatEmoji(0x1F4D6, false),
      new GoogleCompatEmoji(0x1F4D7, false),
      new GoogleCompatEmoji(0x1F4D8, false),
      new GoogleCompatEmoji(0x1F4D9, false),
      new GoogleCompatEmoji(0x1F4DA, false),
      new GoogleCompatEmoji(0x1F4D3, false),
      new GoogleCompatEmoji(0x1F4D2, false),
      new GoogleCompatEmoji(0x1F4C3, false),
      new GoogleCompatEmoji(0x1F4DC, false),
      new GoogleCompatEmoji(0x1F4C4, false),
      new GoogleCompatEmoji(0x1F4F0, false),
      new GoogleCompatEmoji(new int[] { 0x1F5DE, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4D1, false),
      new GoogleCompatEmoji(0x1F516, false),
      new GoogleCompatEmoji(new int[] { 0x1F3F7, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4B0, false),
      new GoogleCompatEmoji(0x1F4B4, false),
      new GoogleCompatEmoji(0x1F4B5, false),
      new GoogleCompatEmoji(0x1F4B6, false),
      new GoogleCompatEmoji(0x1F4B7, false),
      new GoogleCompatEmoji(0x1F4B8, false),
      new GoogleCompatEmoji(0x1F4B3, false),
      new GoogleCompatEmoji(0x1F9FE, false),
      new GoogleCompatEmoji(0x1F4B9, false),
      new GoogleCompatEmoji(0x1F4B1, false),
      new GoogleCompatEmoji(0x1F4B2, false),
      new GoogleCompatEmoji(new int[] { 0x2709, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4E7, false),
      new GoogleCompatEmoji(0x1F4E8, false),
      new GoogleCompatEmoji(0x1F4E9, false),
      new GoogleCompatEmoji(0x1F4E4, false),
      new GoogleCompatEmoji(0x1F4E5, false),
      new GoogleCompatEmoji(0x1F4E6, false),
      new GoogleCompatEmoji(0x1F4EB, false),
      new GoogleCompatEmoji(0x1F4EA, false),
      new GoogleCompatEmoji(0x1F4EC, false),
      new GoogleCompatEmoji(0x1F4ED, false),
      new GoogleCompatEmoji(0x1F4EE, false),
      new GoogleCompatEmoji(new int[] { 0x1F5F3, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x270F, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2712, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F58B, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F58A, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F58C, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F58D, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4DD, false),
      new GoogleCompatEmoji(0x1F4BC, false),
      new GoogleCompatEmoji(0x1F4C1, false),
      new GoogleCompatEmoji(0x1F4C2, false),
      new GoogleCompatEmoji(new int[] { 0x1F5C2, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4C5, false),
      new GoogleCompatEmoji(0x1F4C6, false),
      new GoogleCompatEmoji(new int[] { 0x1F5D2, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5D3, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4C7, false),
      new GoogleCompatEmoji(0x1F4C8, false),
      new GoogleCompatEmoji(0x1F4C9, false),
      new GoogleCompatEmoji(0x1F4CA, false),
      new GoogleCompatEmoji(0x1F4CB, false),
      new GoogleCompatEmoji(0x1F4CC, false),
      new GoogleCompatEmoji(0x1F4CD, false),
      new GoogleCompatEmoji(0x1F4CE, false),
      new GoogleCompatEmoji(new int[] { 0x1F587, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F4CF, false),
      new GoogleCompatEmoji(0x1F4D0, false),
      new GoogleCompatEmoji(new int[] { 0x2702, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5C3, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5C4, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5D1, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F512, false),
      new GoogleCompatEmoji(0x1F513, false),
      new GoogleCompatEmoji(0x1F50F, false),
      new GoogleCompatEmoji(0x1F510, false),
      new GoogleCompatEmoji(0x1F511, false),
      new GoogleCompatEmoji(new int[] { 0x1F5DD, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F528, false),
      new GoogleCompatEmoji(0x1FA93, false),
      new GoogleCompatEmoji(new int[] { 0x26CF, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2692, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E0, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5E1, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2694, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F52B, false),
      new GoogleCompatEmoji(0x1F3F9, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E1, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F527, false),
      new GoogleCompatEmoji(0x1F529, false),
      new GoogleCompatEmoji(new int[] { 0x2699, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F5DC, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2696, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F9AF, false),
      new GoogleCompatEmoji(0x1F517, false),
      new GoogleCompatEmoji(new int[] { 0x26D3, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F9F0, false),
      new GoogleCompatEmoji(0x1F9F2, false),
      new GoogleCompatEmoji(new int[] { 0x2697, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F9EA, false),
      new GoogleCompatEmoji(0x1F9EB, false),
      new GoogleCompatEmoji(0x1F9EC, false),
      new GoogleCompatEmoji(0x1F52C, false),
      new GoogleCompatEmoji(0x1F52D, false),
      new GoogleCompatEmoji(0x1F4E1, false),
      new GoogleCompatEmoji(0x1F489, false),
      new GoogleCompatEmoji(0x1FA78, false),
      new GoogleCompatEmoji(0x1F48A, false),
      new GoogleCompatEmoji(0x1FA79, false),
      new GoogleCompatEmoji(0x1FA7A, false),
      new GoogleCompatEmoji(0x1F6AA, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CF, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CB, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1FA91, false),
      new GoogleCompatEmoji(0x1F6BD, false),
      new GoogleCompatEmoji(0x1F6BF, false),
      new GoogleCompatEmoji(0x1F6C1, false),
      new GoogleCompatEmoji(0x1FA92, false),
      new GoogleCompatEmoji(0x1F9F4, false),
      new GoogleCompatEmoji(0x1F9F7, false),
      new GoogleCompatEmoji(0x1F9F9, false),
      new GoogleCompatEmoji(0x1F9FA, false),
      new GoogleCompatEmoji(0x1F9FB, false),
      new GoogleCompatEmoji(0x1F9FC, false),
      new GoogleCompatEmoji(0x1F9FD, false),
      new GoogleCompatEmoji(0x1F9EF, false),
      new GoogleCompatEmoji(0x1F6D2, false),
      new GoogleCompatEmoji(0x1F6AC, false),
      new GoogleCompatEmoji(new int[] { 0x26B0, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x26B1, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F5FF, false)
    };
  }

  private ObjectsCategoryChunk0() {
    // No instances.
  }
}
