/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class ObjectsCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F453, new String[]{"eyeglasses"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F576, 0xFE0F }, new String[]{"dark_sunglasses"}, false),
      new GoogleCompatEmoji(0x1F97D, new String[]{"goggles"}, false),
      new GoogleCompatEmoji(0x1F97C, new String[]{"lab_coat"}, false),
      new GoogleCompatEmoji(0x1F9BA, new String[]{"safety_vest"}, false),
      new GoogleCompatEmoji(0x1F454, new String[]{"necktie"}, false),
      new GoogleCompatEmoji(0x1F455, new String[]{"shirt", "tshirt"}, false),
      new GoogleCompatEmoji(0x1F456, new String[]{"jeans"}, false),
      new GoogleCompatEmoji(0x1F9E3, new String[]{"scarf"}, false),
      new GoogleCompatEmoji(0x1F9E4, new String[]{"gloves"}, false),
      new GoogleCompatEmoji(0x1F9E5, new String[]{"coat"}, false),
      new GoogleCompatEmoji(0x1F9E6, new String[]{"socks"}, false),
      new GoogleCompatEmoji(0x1F457, new String[]{"dress"}, false),
      new GoogleCompatEmoji(0x1F458, new String[]{"kimono"}, false),
      new GoogleCompatEmoji(0x1F97B, new String[]{"sari"}, false),
      new GoogleCompatEmoji(0x1FA71, new String[]{"one-piece_swimsuit"}, false),
      new GoogleCompatEmoji(0x1FA72, new String[]{"briefs"}, false),
      new GoogleCompatEmoji(0x1FA73, new String[]{"shorts"}, false),
      new GoogleCompatEmoji(0x1F459, new String[]{"bikini"}, false),
      new GoogleCompatEmoji(0x1F45A, new String[]{"womans_clothes"}, false),
      new GoogleCompatEmoji(0x1F45B, new String[]{"purse"}, false),
      new GoogleCompatEmoji(0x1F45C, new String[]{"handbag"}, false),
      new GoogleCompatEmoji(0x1F45D, new String[]{"pouch"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CD, 0xFE0F }, new String[]{"shopping_bags"}, false),
      new GoogleCompatEmoji(0x1F392, new String[]{"school_satchel"}, false),
      new GoogleCompatEmoji(0x1F45E, new String[]{"mans_shoe", "shoe"}, false),
      new GoogleCompatEmoji(0x1F45F, new String[]{"athletic_shoe"}, false),
      new GoogleCompatEmoji(0x1F97E, new String[]{"hiking_boot"}, false),
      new GoogleCompatEmoji(0x1F97F, new String[]{"womans_flat_shoe"}, false),
      new GoogleCompatEmoji(0x1F460, new String[]{"high_heel"}, false),
      new GoogleCompatEmoji(0x1F461, new String[]{"sandal"}, false),
      new GoogleCompatEmoji(0x1FA70, new String[]{"ballet_shoes"}, false),
      new GoogleCompatEmoji(0x1F462, new String[]{"boot"}, false),
      new GoogleCompatEmoji(0x1F451, new String[]{"crown"}, false),
      new GoogleCompatEmoji(0x1F452, new String[]{"womans_hat"}, false),
      new GoogleCompatEmoji(0x1F3A9, new String[]{"tophat"}, false),
      new GoogleCompatEmoji(0x1F393, new String[]{"mortar_board"}, false),
      new GoogleCompatEmoji(0x1F9E2, new String[]{"billed_cap"}, false),
      new GoogleCompatEmoji(new int[] { 0x26D1, 0xFE0F }, new String[]{"helmet_with_white_cross"}, false),
      new GoogleCompatEmoji(0x1F4FF, new String[]{"prayer_beads"}, false),
      new GoogleCompatEmoji(0x1F484, new String[]{"lipstick"}, false),
      new GoogleCompatEmoji(0x1F48D, new String[]{"ring"}, false),
      new GoogleCompatEmoji(0x1F48E, new String[]{"gem"}, false),
      new GoogleCompatEmoji(0x1F507, new String[]{"mute"}, false),
      new GoogleCompatEmoji(0x1F508, new String[]{"speaker"}, false),
      new GoogleCompatEmoji(0x1F509, new String[]{"sound"}, false),
      new GoogleCompatEmoji(0x1F50A, new String[]{"loud_sound"}, false),
      new GoogleCompatEmoji(0x1F4E2, new String[]{"loudspeaker"}, false),
      new GoogleCompatEmoji(0x1F4E3, new String[]{"mega"}, false),
      new GoogleCompatEmoji(0x1F4EF, new String[]{"postal_horn"}, false),
      new GoogleCompatEmoji(0x1F514, new String[]{"bell"}, false),
      new GoogleCompatEmoji(0x1F515, new String[]{"no_bell"}, false),
      new GoogleCompatEmoji(0x1F3BC, new String[]{"musical_score"}, false),
      new GoogleCompatEmoji(0x1F3B5, new String[]{"musical_note"}, false),
      new GoogleCompatEmoji(0x1F3B6, new String[]{"notes"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F399, 0xFE0F }, new String[]{"studio_microphone"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F39A, 0xFE0F }, new String[]{"level_slider"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F39B, 0xFE0F }, new String[]{"control_knobs"}, false),
      new GoogleCompatEmoji(0x1F3A4, new String[]{"microphone"}, false),
      new GoogleCompatEmoji(0x1F3A7, new String[]{"headphones"}, false),
      new GoogleCompatEmoji(0x1F4FB, new String[]{"radio"}, false),
      new GoogleCompatEmoji(0x1F3B7, new String[]{"saxophone"}, false),
      new GoogleCompatEmoji(0x1F3B8, new String[]{"guitar"}, false),
      new GoogleCompatEmoji(0x1F3B9, new String[]{"musical_keyboard"}, false),
      new GoogleCompatEmoji(0x1F3BA, new String[]{"trumpet"}, false),
      new GoogleCompatEmoji(0x1F3BB, new String[]{"violin"}, false),
      new GoogleCompatEmoji(0x1FA95, new String[]{"banjo"}, false),
      new GoogleCompatEmoji(0x1F941, new String[]{"drum_with_drumsticks"}, false),
      new GoogleCompatEmoji(0x1F4F1, new String[]{"iphone"}, false),
      new GoogleCompatEmoji(0x1F4F2, new String[]{"calling"}, false),
      new GoogleCompatEmoji(new int[] { 0x260E, 0xFE0F }, new String[]{"phone", "telephone"}, false),
      new GoogleCompatEmoji(0x1F4DE, new String[]{"telephone_receiver"}, false),
      new GoogleCompatEmoji(0x1F4DF, new String[]{"pager"}, false),
      new GoogleCompatEmoji(0x1F4E0, new String[]{"fax"}, false),
      new GoogleCompatEmoji(0x1F50B, new String[]{"battery"}, false),
      new GoogleCompatEmoji(0x1F50C, new String[]{"electric_plug"}, false),
      new GoogleCompatEmoji(0x1F4BB, new String[]{"computer"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5A5, 0xFE0F }, new String[]{"desktop_computer"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5A8, 0xFE0F }, new String[]{"printer"}, false),
      new GoogleCompatEmoji(new int[] { 0x2328, 0xFE0F }, new String[]{"keyboard"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5B1, 0xFE0F }, new String[]{"three_button_mouse"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5B2, 0xFE0F }, new String[]{"trackball"}, false),
      new GoogleCompatEmoji(0x1F4BD, new String[]{"minidisc"}, false),
      new GoogleCompatEmoji(0x1F4BE, new String[]{"floppy_disk"}, false),
      new GoogleCompatEmoji(0x1F4BF, new String[]{"cd"}, false),
      new GoogleCompatEmoji(0x1F4C0, new String[]{"dvd"}, false),
      new GoogleCompatEmoji(0x1F9EE, new String[]{"abacus"}, false),
      new GoogleCompatEmoji(0x1F3A5, new String[]{"movie_camera"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F39E, 0xFE0F }, new String[]{"film_frames"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F4FD, 0xFE0F }, new String[]{"film_projector"}, false),
      new GoogleCompatEmoji(0x1F3AC, new String[]{"clapper"}, false),
      new GoogleCompatEmoji(0x1F4FA, new String[]{"tv"}, false),
      new GoogleCompatEmoji(0x1F4F7, new String[]{"camera"}, false),
      new GoogleCompatEmoji(0x1F4F8, new String[]{"camera_with_flash"}, false),
      new GoogleCompatEmoji(0x1F4F9, new String[]{"video_camera"}, false),
      new GoogleCompatEmoji(0x1F4FC, new String[]{"vhs"}, false),
      new GoogleCompatEmoji(0x1F50D, new String[]{"mag"}, false),
      new GoogleCompatEmoji(0x1F50E, new String[]{"mag_right"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F56F, 0xFE0F }, new String[]{"candle"}, false),
      new GoogleCompatEmoji(0x1F4A1, new String[]{"bulb"}, false),
      new GoogleCompatEmoji(0x1F526, new String[]{"flashlight"}, false),
      new GoogleCompatEmoji(0x1F3EE, new String[]{"izakaya_lantern", "lantern"}, false),
      new GoogleCompatEmoji(0x1FA94, new String[]{"diya_lamp"}, false),
      new GoogleCompatEmoji(0x1F4D4, new String[]{"notebook_with_decorative_cover"}, false),
      new GoogleCompatEmoji(0x1F4D5, new String[]{"closed_book"}, false),
      new GoogleCompatEmoji(0x1F4D6, new String[]{"book", "open_book"}, false),
      new GoogleCompatEmoji(0x1F4D7, new String[]{"green_book"}, false),
      new GoogleCompatEmoji(0x1F4D8, new String[]{"blue_book"}, false),
      new GoogleCompatEmoji(0x1F4D9, new String[]{"orange_book"}, false),
      new GoogleCompatEmoji(0x1F4DA, new String[]{"books"}, false),
      new GoogleCompatEmoji(0x1F4D3, new String[]{"notebook"}, false),
      new GoogleCompatEmoji(0x1F4D2, new String[]{"ledger"}, false),
      new GoogleCompatEmoji(0x1F4C3, new String[]{"page_with_curl"}, false),
      new GoogleCompatEmoji(0x1F4DC, new String[]{"scroll"}, false),
      new GoogleCompatEmoji(0x1F4C4, new String[]{"page_facing_up"}, false),
      new GoogleCompatEmoji(0x1F4F0, new String[]{"newspaper"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5DE, 0xFE0F }, new String[]{"rolled_up_newspaper"}, false),
      new GoogleCompatEmoji(0x1F4D1, new String[]{"bookmark_tabs"}, false),
      new GoogleCompatEmoji(0x1F516, new String[]{"bookmark"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3F7, 0xFE0F }, new String[]{"label"}, false),
      new GoogleCompatEmoji(0x1F4B0, new String[]{"moneybag"}, false),
      new GoogleCompatEmoji(0x1F4B4, new String[]{"yen"}, false),
      new GoogleCompatEmoji(0x1F4B5, new String[]{"dollar"}, false),
      new GoogleCompatEmoji(0x1F4B6, new String[]{"euro"}, false),
      new GoogleCompatEmoji(0x1F4B7, new String[]{"pound"}, false),
      new GoogleCompatEmoji(0x1F4B8, new String[]{"money_with_wings"}, false),
      new GoogleCompatEmoji(0x1F4B3, new String[]{"credit_card"}, false),
      new GoogleCompatEmoji(0x1F9FE, new String[]{"receipt"}, false),
      new GoogleCompatEmoji(0x1F4B9, new String[]{"chart"}, false),
      new GoogleCompatEmoji(0x1F4B1, new String[]{"currency_exchange"}, false),
      new GoogleCompatEmoji(0x1F4B2, new String[]{"heavy_dollar_sign"}, false),
      new GoogleCompatEmoji(new int[] { 0x2709, 0xFE0F }, new String[]{"email", "envelope"}, false),
      new GoogleCompatEmoji(0x1F4E7, new String[]{"e-mail"}, false),
      new GoogleCompatEmoji(0x1F4E8, new String[]{"incoming_envelope"}, false),
      new GoogleCompatEmoji(0x1F4E9, new String[]{"envelope_with_arrow"}, false),
      new GoogleCompatEmoji(0x1F4E4, new String[]{"outbox_tray"}, false),
      new GoogleCompatEmoji(0x1F4E5, new String[]{"inbox_tray"}, false),
      new GoogleCompatEmoji(0x1F4E6, new String[]{"package"}, false),
      new GoogleCompatEmoji(0x1F4EB, new String[]{"mailbox"}, false),
      new GoogleCompatEmoji(0x1F4EA, new String[]{"mailbox_closed"}, false),
      new GoogleCompatEmoji(0x1F4EC, new String[]{"mailbox_with_mail"}, false),
      new GoogleCompatEmoji(0x1F4ED, new String[]{"mailbox_with_no_mail"}, false),
      new GoogleCompatEmoji(0x1F4EE, new String[]{"postbox"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5F3, 0xFE0F }, new String[]{"ballot_box_with_ballot"}, false),
      new GoogleCompatEmoji(new int[] { 0x270F, 0xFE0F }, new String[]{"pencil2"}, false),
      new GoogleCompatEmoji(new int[] { 0x2712, 0xFE0F }, new String[]{"black_nib"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F58B, 0xFE0F }, new String[]{"lower_left_fountain_pen"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F58A, 0xFE0F }, new String[]{"lower_left_ballpoint_pen"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F58C, 0xFE0F }, new String[]{"lower_left_paintbrush"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F58D, 0xFE0F }, new String[]{"lower_left_crayon"}, false),
      new GoogleCompatEmoji(0x1F4DD, new String[]{"memo", "pencil"}, false),
      new GoogleCompatEmoji(0x1F4BC, new String[]{"briefcase"}, false),
      new GoogleCompatEmoji(0x1F4C1, new String[]{"file_folder"}, false),
      new GoogleCompatEmoji(0x1F4C2, new String[]{"open_file_folder"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5C2, 0xFE0F }, new String[]{"card_index_dividers"}, false),
      new GoogleCompatEmoji(0x1F4C5, new String[]{"date"}, false),
      new GoogleCompatEmoji(0x1F4C6, new String[]{"calendar"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5D2, 0xFE0F }, new String[]{"spiral_note_pad"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5D3, 0xFE0F }, new String[]{"spiral_calendar_pad"}, false),
      new GoogleCompatEmoji(0x1F4C7, new String[]{"card_index"}, false),
      new GoogleCompatEmoji(0x1F4C8, new String[]{"chart_with_upwards_trend"}, false),
      new GoogleCompatEmoji(0x1F4C9, new String[]{"chart_with_downwards_trend"}, false),
      new GoogleCompatEmoji(0x1F4CA, new String[]{"bar_chart"}, false),
      new GoogleCompatEmoji(0x1F4CB, new String[]{"clipboard"}, false),
      new GoogleCompatEmoji(0x1F4CC, new String[]{"pushpin"}, false),
      new GoogleCompatEmoji(0x1F4CD, new String[]{"round_pushpin"}, false),
      new GoogleCompatEmoji(0x1F4CE, new String[]{"paperclip"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F587, 0xFE0F }, new String[]{"linked_paperclips"}, false),
      new GoogleCompatEmoji(0x1F4CF, new String[]{"straight_ruler"}, false),
      new GoogleCompatEmoji(0x1F4D0, new String[]{"triangular_ruler"}, false),
      new GoogleCompatEmoji(new int[] { 0x2702, 0xFE0F }, new String[]{"scissors"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5C3, 0xFE0F }, new String[]{"card_file_box"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5C4, 0xFE0F }, new String[]{"file_cabinet"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5D1, 0xFE0F }, new String[]{"wastebasket"}, false),
      new GoogleCompatEmoji(0x1F512, new String[]{"lock"}, false),
      new GoogleCompatEmoji(0x1F513, new String[]{"unlock"}, false),
      new GoogleCompatEmoji(0x1F50F, new String[]{"lock_with_ink_pen"}, false),
      new GoogleCompatEmoji(0x1F510, new String[]{"closed_lock_with_key"}, false),
      new GoogleCompatEmoji(0x1F511, new String[]{"key"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5DD, 0xFE0F }, new String[]{"old_key"}, false),
      new GoogleCompatEmoji(0x1F528, new String[]{"hammer"}, false),
      new GoogleCompatEmoji(0x1FA93, new String[]{"axe"}, false),
      new GoogleCompatEmoji(new int[] { 0x26CF, 0xFE0F }, new String[]{"pick"}, false),
      new GoogleCompatEmoji(new int[] { 0x2692, 0xFE0F }, new String[]{"hammer_and_pick"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E0, 0xFE0F }, new String[]{"hammer_and_wrench"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5E1, 0xFE0F }, new String[]{"dagger_knife"}, false),
      new GoogleCompatEmoji(new int[] { 0x2694, 0xFE0F }, new String[]{"crossed_swords"}, false),
      new GoogleCompatEmoji(0x1F52B, new String[]{"gun"}, false),
      new GoogleCompatEmoji(0x1F3F9, new String[]{"bow_and_arrow"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E1, 0xFE0F }, new String[]{"shield"}, false),
      new GoogleCompatEmoji(0x1F527, new String[]{"wrench"}, false),
      new GoogleCompatEmoji(0x1F529, new String[]{"nut_and_bolt"}, false),
      new GoogleCompatEmoji(new int[] { 0x2699, 0xFE0F }, new String[]{"gear"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5DC, 0xFE0F }, new String[]{"compression"}, false),
      new GoogleCompatEmoji(new int[] { 0x2696, 0xFE0F }, new String[]{"scales"}, false),
      new GoogleCompatEmoji(0x1F9AF, new String[]{"probing_cane"}, false),
      new GoogleCompatEmoji(0x1F517, new String[]{"link"}, false),
      new GoogleCompatEmoji(new int[] { 0x26D3, 0xFE0F }, new String[]{"chains"}, false),
      new GoogleCompatEmoji(0x1F9F0, new String[]{"toolbox"}, false),
      new GoogleCompatEmoji(0x1F9F2, new String[]{"magnet"}, false),
      new GoogleCompatEmoji(new int[] { 0x2697, 0xFE0F }, new String[]{"alembic"}, false),
      new GoogleCompatEmoji(0x1F9EA, new String[]{"test_tube"}, false),
      new GoogleCompatEmoji(0x1F9EB, new String[]{"petri_dish"}, false),
      new GoogleCompatEmoji(0x1F9EC, new String[]{"dna"}, false),
      new GoogleCompatEmoji(0x1F52C, new String[]{"microscope"}, false),
      new GoogleCompatEmoji(0x1F52D, new String[]{"telescope"}, false),
      new GoogleCompatEmoji(0x1F4E1, new String[]{"satellite_antenna"}, false),
      new GoogleCompatEmoji(0x1F489, new String[]{"syringe"}, false),
      new GoogleCompatEmoji(0x1FA78, new String[]{"drop_of_blood"}, false),
      new GoogleCompatEmoji(0x1F48A, new String[]{"pill"}, false),
      new GoogleCompatEmoji(0x1FA79, new String[]{"adhesive_bandage"}, false),
      new GoogleCompatEmoji(0x1FA7A, new String[]{"stethoscope"}, false),
      new GoogleCompatEmoji(0x1F6AA, new String[]{"door"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CF, 0xFE0F }, new String[]{"bed"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CB, 0xFE0F }, new String[]{"couch_and_lamp"}, false),
      new GoogleCompatEmoji(0x1FA91, new String[]{"chair"}, false),
      new GoogleCompatEmoji(0x1F6BD, new String[]{"toilet"}, false),
      new GoogleCompatEmoji(0x1F6BF, new String[]{"shower"}, false),
      new GoogleCompatEmoji(0x1F6C1, new String[]{"bathtub"}, false),
      new GoogleCompatEmoji(0x1FA92, new String[]{"razor"}, false),
      new GoogleCompatEmoji(0x1F9F4, new String[]{"lotion_bottle"}, false),
      new GoogleCompatEmoji(0x1F9F7, new String[]{"safety_pin"}, false),
      new GoogleCompatEmoji(0x1F9F9, new String[]{"broom"}, false),
      new GoogleCompatEmoji(0x1F9FA, new String[]{"basket"}, false),
      new GoogleCompatEmoji(0x1F9FB, new String[]{"roll_of_paper"}, false),
      new GoogleCompatEmoji(0x1F9FC, new String[]{"soap"}, false),
      new GoogleCompatEmoji(0x1F9FD, new String[]{"sponge"}, false),
      new GoogleCompatEmoji(0x1F9EF, new String[]{"fire_extinguisher"}, false),
      new GoogleCompatEmoji(0x1F6D2, new String[]{"shopping_trolley"}, false),
      new GoogleCompatEmoji(0x1F6AC, new String[]{"smoking"}, false),
      new GoogleCompatEmoji(new int[] { 0x26B0, 0xFE0F }, new String[]{"coffin"}, false),
      new GoogleCompatEmoji(new int[] { 0x26B1, 0xFE0F }, new String[]{"funeral_urn"}, false),
      new GoogleCompatEmoji(0x1F5FF, new String[]{"moyai"}, false)
    };
  }

  private ObjectsCategoryChunk0() {
    // No instances.
  }
}
