package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class SymbolsCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F3E7, false),
      new GoogleCompatEmoji(0x1F6AE, false),
      new GoogleCompatEmoji(0x1F6B0, false),
      new GoogleCompatEmoji(0x267F, false),
      new GoogleCompatEmoji(0x1F6B9, false),
      new GoogleCompatEmoji(0x1F6BA, false),
      new GoogleCompatEmoji(0x1F6BB, false),
      new GoogleCompatEmoji(0x1F6BC, false),
      new GoogleCompatEmoji(0x1F6BE, false),
      new GoogleCompatEmoji(0x1F6C2, false),
      new GoogleCompatEmoji(0x1F6C3, false),
      new GoogleCompatEmoji(0x1F6C4, false),
      new GoogleCompatEmoji(0x1F6C5, false),
      new GoogleCompatEmoji(new int[] { 0x26A0, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F6B8, false),
      new GoogleCompatEmoji(0x26D4, false),
      new GoogleCompatEmoji(0x1F6AB, false),
      new GoogleCompatEmoji(0x1F6B3, false),
      new GoogleCompatEmoji(0x1F6AD, false),
      new GoogleCompatEmoji(0x1F6AF, false),
      new GoogleCompatEmoji(0x1F6B1, false),
      new GoogleCompatEmoji(0x1F6B7, false),
      new GoogleCompatEmoji(0x1F4F5, false),
      new GoogleCompatEmoji(0x1F51E, false),
      new GoogleCompatEmoji(new int[] { 0x2622, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2623, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2B06, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2197, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x27A1, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2198, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2B07, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2199, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2B05, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2196, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2195, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2194, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x21A9, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x21AA, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2934, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2935, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F503, false),
      new GoogleCompatEmoji(0x1F504, false),
      new GoogleCompatEmoji(0x1F519, false),
      new GoogleCompatEmoji(0x1F51A, false),
      new GoogleCompatEmoji(0x1F51B, false),
      new GoogleCompatEmoji(0x1F51C, false),
      new GoogleCompatEmoji(0x1F51D, false),
      new GoogleCompatEmoji(0x1F6D0, false),
      new GoogleCompatEmoji(new int[] { 0x269B, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F549, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2721, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2638, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x262F, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x271D, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2626, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x262A, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x262E, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F54E, false),
      new GoogleCompatEmoji(0x1F52F, false),
      new GoogleCompatEmoji(0x2648, false),
      new GoogleCompatEmoji(0x2649, false),
      new GoogleCompatEmoji(0x264A, false),
      new GoogleCompatEmoji(0x264B, false),
      new GoogleCompatEmoji(0x264C, false),
      new GoogleCompatEmoji(0x264D, false),
      new GoogleCompatEmoji(0x264E, false),
      new GoogleCompatEmoji(0x264F, false),
      new GoogleCompatEmoji(0x2650, false),
      new GoogleCompatEmoji(0x2651, false),
      new GoogleCompatEmoji(0x2652, false),
      new GoogleCompatEmoji(0x2653, false),
      new GoogleCompatEmoji(0x26CE, false),
      new GoogleCompatEmoji(0x1F500, false),
      new GoogleCompatEmoji(0x1F501, false),
      new GoogleCompatEmoji(0x1F502, false),
      new GoogleCompatEmoji(new int[] { 0x25B6, 0xFE0F }, false),
      new GoogleCompatEmoji(0x23E9, false),
      new GoogleCompatEmoji(new int[] { 0x23ED, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x23EF, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x25C0, 0xFE0F }, false),
      new GoogleCompatEmoji(0x23EA, false),
      new GoogleCompatEmoji(new int[] { 0x23EE, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F53C, false),
      new GoogleCompatEmoji(0x23EB, false),
      new GoogleCompatEmoji(0x1F53D, false),
      new GoogleCompatEmoji(0x23EC, false),
      new GoogleCompatEmoji(new int[] { 0x23F8, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x23F9, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x23FA, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x23CF, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3A6, false),
      new GoogleCompatEmoji(0x1F505, false),
      new GoogleCompatEmoji(0x1F506, false),
      new GoogleCompatEmoji(0x1F4F6, false),
      new GoogleCompatEmoji(0x1F4F3, false),
      new GoogleCompatEmoji(0x1F4F4, false),
      new GoogleCompatEmoji(new int[] { 0x2640, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2642, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2695, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x267E, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x267B, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x269C, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F531, false),
      new GoogleCompatEmoji(0x1F4DB, false),
      new GoogleCompatEmoji(0x1F530, false),
      new GoogleCompatEmoji(0x2B55, false),
      new GoogleCompatEmoji(0x2705, false),
      new GoogleCompatEmoji(new int[] { 0x2611, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2714, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2716, 0xFE0F }, false),
      new GoogleCompatEmoji(0x274C, false),
      new GoogleCompatEmoji(0x274E, false),
      new GoogleCompatEmoji(0x2795, false),
      new GoogleCompatEmoji(0x2796, false),
      new GoogleCompatEmoji(0x2797, false),
      new GoogleCompatEmoji(0x27B0, false),
      new GoogleCompatEmoji(0x27BF, false),
      new GoogleCompatEmoji(new int[] { 0x303D, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2733, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2734, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2747, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x203C, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2049, 0xFE0F }, false),
      new GoogleCompatEmoji(0x2753, false),
      new GoogleCompatEmoji(0x2754, false),
      new GoogleCompatEmoji(0x2755, false),
      new GoogleCompatEmoji(0x2757, false),
      new GoogleCompatEmoji(new int[] { 0x3030, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x00A9, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x00AE, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2122, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x0023, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x002A, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0030, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0031, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0032, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0033, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0034, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0035, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0036, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0037, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0038, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(new int[] { 0x0039, 0xFE0F, 0x20E3 }, false),
      new GoogleCompatEmoji(0x1F51F, false),
      new GoogleCompatEmoji(0x1F520, false),
      new GoogleCompatEmoji(0x1F521, false),
      new GoogleCompatEmoji(0x1F522, false),
      new GoogleCompatEmoji(0x1F523, false),
      new GoogleCompatEmoji(0x1F524, false),
      new GoogleCompatEmoji(new int[] { 0x1F170, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F18E, false),
      new GoogleCompatEmoji(new int[] { 0x1F171, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F191, false),
      new GoogleCompatEmoji(0x1F192, false),
      new GoogleCompatEmoji(0x1F193, false),
      new GoogleCompatEmoji(new int[] { 0x2139, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F194, false),
      new GoogleCompatEmoji(new int[] { 0x24C2, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F195, false),
      new GoogleCompatEmoji(0x1F196, false),
      new GoogleCompatEmoji(new int[] { 0x1F17E, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F197, false),
      new GoogleCompatEmoji(new int[] { 0x1F17F, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F198, false),
      new GoogleCompatEmoji(0x1F199, false),
      new GoogleCompatEmoji(0x1F19A, false),
      new GoogleCompatEmoji(0x1F201, false),
      new GoogleCompatEmoji(new int[] { 0x1F202, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F237, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F236, false),
      new GoogleCompatEmoji(0x1F22F, false),
      new GoogleCompatEmoji(0x1F250, false),
      new GoogleCompatEmoji(0x1F239, false),
      new GoogleCompatEmoji(0x1F21A, false),
      new GoogleCompatEmoji(0x1F232, false),
      new GoogleCompatEmoji(0x1F251, false),
      new GoogleCompatEmoji(0x1F238, false),
      new GoogleCompatEmoji(0x1F234, false),
      new GoogleCompatEmoji(0x1F233, false),
      new GoogleCompatEmoji(new int[] { 0x3297, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x3299, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F23A, false),
      new GoogleCompatEmoji(0x1F235, false),
      new GoogleCompatEmoji(0x1F534, false),
      new GoogleCompatEmoji(0x1F7E0, false),
      new GoogleCompatEmoji(0x1F7E1, false),
      new GoogleCompatEmoji(0x1F7E2, false),
      new GoogleCompatEmoji(0x1F535, false),
      new GoogleCompatEmoji(0x1F7E3, false),
      new GoogleCompatEmoji(0x1F7E4, false),
      new GoogleCompatEmoji(0x26AB, false),
      new GoogleCompatEmoji(0x26AA, false),
      new GoogleCompatEmoji(0x1F7E5, false),
      new GoogleCompatEmoji(0x1F7E7, false),
      new GoogleCompatEmoji(0x1F7E8, false),
      new GoogleCompatEmoji(0x1F7E9, false),
      new GoogleCompatEmoji(0x1F7E6, false),
      new GoogleCompatEmoji(0x1F7EA, false),
      new GoogleCompatEmoji(0x1F7EB, false),
      new GoogleCompatEmoji(0x2B1B, false),
      new GoogleCompatEmoji(0x2B1C, false),
      new GoogleCompatEmoji(new int[] { 0x25FC, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x25FB, 0xFE0F }, false),
      new GoogleCompatEmoji(0x25FE, false),
      new GoogleCompatEmoji(0x25FD, false),
      new GoogleCompatEmoji(new int[] { 0x25AA, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x25AB, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F536, false),
      new GoogleCompatEmoji(0x1F537, false),
      new GoogleCompatEmoji(0x1F538, false),
      new GoogleCompatEmoji(0x1F539, false),
      new GoogleCompatEmoji(0x1F53A, false),
      new GoogleCompatEmoji(0x1F53B, false),
      new GoogleCompatEmoji(0x1F4A0, false),
      new GoogleCompatEmoji(0x1F518, false),
      new GoogleCompatEmoji(0x1F533, false),
      new GoogleCompatEmoji(0x1F532, false)
    };
  }

  private SymbolsCategoryChunk0() {
    // No instances.
  }
}
