package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class TravelAndPlacesCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F30D, new String[]{"earth_africa"}, false),
      new GoogleCompatEmoji(0x1F30E, new String[]{"earth_americas"}, false),
      new GoogleCompatEmoji(0x1F30F, new String[]{"earth_asia"}, false),
      new GoogleCompatEmoji(0x1F310, new String[]{"globe_with_meridians"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F5FA, 0xFE0F }, new String[]{"world_map"}, false),
      new GoogleCompatEmoji(0x1F5FE, new String[]{"japan"}, false),
      new GoogleCompatEmoji(0x1F9ED, new String[]{"compass"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D4, 0xFE0F }, new String[]{"snow_capped_mountain"}, false),
      new GoogleCompatEmoji(new int[] { 0x26F0, 0xFE0F }, new String[]{"mountain"}, false),
      new GoogleCompatEmoji(0x1F30B, new String[]{"volcano"}, false),
      new GoogleCompatEmoji(0x1F5FB, new String[]{"mount_fuji"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D5, 0xFE0F }, new String[]{"camping"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D6, 0xFE0F }, new String[]{"beach_with_umbrella"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DC, 0xFE0F }, new String[]{"desert"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DD, 0xFE0F }, new String[]{"desert_island"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DE, 0xFE0F }, new String[]{"national_park"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DF, 0xFE0F }, new String[]{"stadium"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DB, 0xFE0F }, new String[]{"classical_building"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D7, 0xFE0F }, new String[]{"building_construction"}, false),
      new GoogleCompatEmoji(0x1F9F1, new String[]{"bricks"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D8, 0xFE0F }, new String[]{"house_buildings"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DA, 0xFE0F }, new String[]{"derelict_house_building"}, false),
      new GoogleCompatEmoji(0x1F3E0, new String[]{"house"}, false),
      new GoogleCompatEmoji(0x1F3E1, new String[]{"house_with_garden"}, false),
      new GoogleCompatEmoji(0x1F3E2, new String[]{"office"}, false),
      new GoogleCompatEmoji(0x1F3E3, new String[]{"post_office"}, false),
      new GoogleCompatEmoji(0x1F3E4, new String[]{"european_post_office"}, false),
      new GoogleCompatEmoji(0x1F3E5, new String[]{"hospital"}, false),
      new GoogleCompatEmoji(0x1F3E6, new String[]{"bank"}, false),
      new GoogleCompatEmoji(0x1F3E8, new String[]{"hotel"}, false),
      new GoogleCompatEmoji(0x1F3E9, new String[]{"love_hotel"}, false),
      new GoogleCompatEmoji(0x1F3EA, new String[]{"convenience_store"}, false),
      new GoogleCompatEmoji(0x1F3EB, new String[]{"school"}, false),
      new GoogleCompatEmoji(0x1F3EC, new String[]{"department_store"}, false),
      new GoogleCompatEmoji(0x1F3ED, new String[]{"factory"}, false),
      new GoogleCompatEmoji(0x1F3EF, new String[]{"japanese_castle"}, false),
      new GoogleCompatEmoji(0x1F3F0, new String[]{"european_castle"}, false),
      new GoogleCompatEmoji(0x1F492, new String[]{"wedding"}, false),
      new GoogleCompatEmoji(0x1F5FC, new String[]{"tokyo_tower"}, false),
      new GoogleCompatEmoji(0x1F5FD, new String[]{"statue_of_liberty"}, false),
      new GoogleCompatEmoji(0x26EA, new String[]{"church"}, false),
      new GoogleCompatEmoji(0x1F54C, new String[]{"mosque"}, false),
      new GoogleCompatEmoji(0x1F6D5, new String[]{"hindu_temple"}, false),
      new GoogleCompatEmoji(0x1F54D, new String[]{"synagogue"}, false),
      new GoogleCompatEmoji(new int[] { 0x26E9, 0xFE0F }, new String[]{"shinto_shrine"}, false),
      new GoogleCompatEmoji(0x1F54B, new String[]{"kaaba"}, false),
      new GoogleCompatEmoji(0x26F2, new String[]{"fountain"}, false),
      new GoogleCompatEmoji(0x26FA, new String[]{"tent"}, false),
      new GoogleCompatEmoji(0x1F301, new String[]{"foggy"}, false),
      new GoogleCompatEmoji(0x1F303, new String[]{"night_with_stars"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D9, 0xFE0F }, new String[]{"cityscape"}, false),
      new GoogleCompatEmoji(0x1F304, new String[]{"sunrise_over_mountains"}, false),
      new GoogleCompatEmoji(0x1F305, new String[]{"sunrise"}, false),
      new GoogleCompatEmoji(0x1F306, new String[]{"city_sunset"}, false),
      new GoogleCompatEmoji(0x1F307, new String[]{"city_sunrise"}, false),
      new GoogleCompatEmoji(0x1F309, new String[]{"bridge_at_night"}, false),
      new GoogleCompatEmoji(new int[] { 0x2668, 0xFE0F }, new String[]{"hotsprings"}, false),
      new GoogleCompatEmoji(0x1F3A0, new String[]{"carousel_horse"}, false),
      new GoogleCompatEmoji(0x1F3A1, new String[]{"ferris_wheel"}, false),
      new GoogleCompatEmoji(0x1F3A2, new String[]{"roller_coaster"}, false),
      new GoogleCompatEmoji(0x1F488, new String[]{"barber"}, false),
      new GoogleCompatEmoji(0x1F3AA, new String[]{"circus_tent"}, false),
      new GoogleCompatEmoji(0x1F682, new String[]{"steam_locomotive"}, false),
      new GoogleCompatEmoji(0x1F683, new String[]{"railway_car"}, false),
      new GoogleCompatEmoji(0x1F684, new String[]{"bullettrain_side"}, false),
      new GoogleCompatEmoji(0x1F685, new String[]{"bullettrain_front"}, false),
      new GoogleCompatEmoji(0x1F686, new String[]{"train2"}, false),
      new GoogleCompatEmoji(0x1F687, new String[]{"metro"}, false),
      new GoogleCompatEmoji(0x1F688, new String[]{"light_rail"}, false),
      new GoogleCompatEmoji(0x1F689, new String[]{"station"}, false),
      new GoogleCompatEmoji(0x1F68A, new String[]{"tram"}, false),
      new GoogleCompatEmoji(0x1F69D, new String[]{"monorail"}, false),
      new GoogleCompatEmoji(0x1F69E, new String[]{"mountain_railway"}, false),
      new GoogleCompatEmoji(0x1F68B, new String[]{"train"}, false),
      new GoogleCompatEmoji(0x1F68C, new String[]{"bus"}, false),
      new GoogleCompatEmoji(0x1F68D, new String[]{"oncoming_bus"}, false),
      new GoogleCompatEmoji(0x1F68E, new String[]{"trolleybus"}, false),
      new GoogleCompatEmoji(0x1F690, new String[]{"minibus"}, false),
      new GoogleCompatEmoji(0x1F691, new String[]{"ambulance"}, false),
      new GoogleCompatEmoji(0x1F692, new String[]{"fire_engine"}, false),
      new GoogleCompatEmoji(0x1F693, new String[]{"police_car"}, false),
      new GoogleCompatEmoji(0x1F694, new String[]{"oncoming_police_car"}, false),
      new GoogleCompatEmoji(0x1F695, new String[]{"taxi"}, false),
      new GoogleCompatEmoji(0x1F696, new String[]{"oncoming_taxi"}, false),
      new GoogleCompatEmoji(0x1F697, new String[]{"car", "red_car"}, false),
      new GoogleCompatEmoji(0x1F698, new String[]{"oncoming_automobile"}, false),
      new GoogleCompatEmoji(0x1F699, new String[]{"blue_car"}, false),
      new GoogleCompatEmoji(0x1F69A, new String[]{"truck"}, false),
      new GoogleCompatEmoji(0x1F69B, new String[]{"articulated_lorry"}, false),
      new GoogleCompatEmoji(0x1F69C, new String[]{"tractor"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3CE, 0xFE0F }, new String[]{"racing_car"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F3CD, 0xFE0F }, new String[]{"racing_motorcycle"}, false),
      new GoogleCompatEmoji(0x1F6F5, new String[]{"motor_scooter"}, false),
      new GoogleCompatEmoji(0x1F9BD, new String[]{"manual_wheelchair"}, false),
      new GoogleCompatEmoji(0x1F9BC, new String[]{"motorized_wheelchair"}, false),
      new GoogleCompatEmoji(0x1F6FA, new String[]{"auto_rickshaw"}, false),
      new GoogleCompatEmoji(0x1F6B2, new String[]{"bike"}, false),
      new GoogleCompatEmoji(0x1F6F4, new String[]{"scooter"}, false),
      new GoogleCompatEmoji(0x1F6F9, new String[]{"skateboard"}, false),
      new GoogleCompatEmoji(0x1F68F, new String[]{"busstop"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E3, 0xFE0F }, new String[]{"motorway"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E4, 0xFE0F }, new String[]{"railway_track"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E2, 0xFE0F }, new String[]{"oil_drum"}, false),
      new GoogleCompatEmoji(0x26FD, new String[]{"fuelpump"}, false),
      new GoogleCompatEmoji(0x1F6A8, new String[]{"rotating_light"}, false),
      new GoogleCompatEmoji(0x1F6A5, new String[]{"traffic_light"}, false),
      new GoogleCompatEmoji(0x1F6A6, new String[]{"vertical_traffic_light"}, false),
      new GoogleCompatEmoji(0x1F6D1, new String[]{"octagonal_sign"}, false),
      new GoogleCompatEmoji(0x1F6A7, new String[]{"construction"}, false),
      new GoogleCompatEmoji(0x2693, new String[]{"anchor"}, false),
      new GoogleCompatEmoji(0x26F5, new String[]{"boat", "sailboat"}, false),
      new GoogleCompatEmoji(0x1F6F6, new String[]{"canoe"}, false),
      new GoogleCompatEmoji(0x1F6A4, new String[]{"speedboat"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6F3, 0xFE0F }, new String[]{"passenger_ship"}, false),
      new GoogleCompatEmoji(new int[] { 0x26F4, 0xFE0F }, new String[]{"ferry"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E5, 0xFE0F }, new String[]{"motor_boat"}, false),
      new GoogleCompatEmoji(0x1F6A2, new String[]{"ship"}, false),
      new GoogleCompatEmoji(new int[] { 0x2708, 0xFE0F }, new String[]{"airplane"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E9, 0xFE0F }, new String[]{"small_airplane"}, false),
      new GoogleCompatEmoji(0x1F6EB, new String[]{"airplane_departure"}, false),
      new GoogleCompatEmoji(0x1F6EC, new String[]{"airplane_arriving"}, false),
      new GoogleCompatEmoji(0x1FA82, new String[]{"parachute"}, false),
      new GoogleCompatEmoji(0x1F4BA, new String[]{"seat"}, false),
      new GoogleCompatEmoji(0x1F681, new String[]{"helicopter"}, false),
      new GoogleCompatEmoji(0x1F69F, new String[]{"suspension_railway"}, false),
      new GoogleCompatEmoji(0x1F6A0, new String[]{"mountain_cableway"}, false),
      new GoogleCompatEmoji(0x1F6A1, new String[]{"aerial_tramway"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6F0, 0xFE0F }, new String[]{"satellite"}, false),
      new GoogleCompatEmoji(0x1F680, new String[]{"rocket"}, false),
      new GoogleCompatEmoji(0x1F6F8, new String[]{"flying_saucer"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CE, 0xFE0F }, new String[]{"bellhop_bell"}, false),
      new GoogleCompatEmoji(0x1F9F3, new String[]{"luggage"}, false),
      new GoogleCompatEmoji(0x231B, new String[]{"hourglass"}, false),
      new GoogleCompatEmoji(0x23F3, new String[]{"hourglass_flowing_sand"}, false),
      new GoogleCompatEmoji(0x231A, new String[]{"watch"}, false),
      new GoogleCompatEmoji(0x23F0, new String[]{"alarm_clock"}, false),
      new GoogleCompatEmoji(new int[] { 0x23F1, 0xFE0F }, new String[]{"stopwatch"}, false),
      new GoogleCompatEmoji(new int[] { 0x23F2, 0xFE0F }, new String[]{"timer_clock"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F570, 0xFE0F }, new String[]{"mantelpiece_clock"}, false),
      new GoogleCompatEmoji(0x1F55B, new String[]{"clock12"}, false),
      new GoogleCompatEmoji(0x1F567, new String[]{"clock1230"}, false),
      new GoogleCompatEmoji(0x1F550, new String[]{"clock1"}, false),
      new GoogleCompatEmoji(0x1F55C, new String[]{"clock130"}, false),
      new GoogleCompatEmoji(0x1F551, new String[]{"clock2"}, false),
      new GoogleCompatEmoji(0x1F55D, new String[]{"clock230"}, false),
      new GoogleCompatEmoji(0x1F552, new String[]{"clock3"}, false),
      new GoogleCompatEmoji(0x1F55E, new String[]{"clock330"}, false),
      new GoogleCompatEmoji(0x1F553, new String[]{"clock4"}, false),
      new GoogleCompatEmoji(0x1F55F, new String[]{"clock430"}, false),
      new GoogleCompatEmoji(0x1F554, new String[]{"clock5"}, false),
      new GoogleCompatEmoji(0x1F560, new String[]{"clock530"}, false),
      new GoogleCompatEmoji(0x1F555, new String[]{"clock6"}, false),
      new GoogleCompatEmoji(0x1F561, new String[]{"clock630"}, false),
      new GoogleCompatEmoji(0x1F556, new String[]{"clock7"}, false),
      new GoogleCompatEmoji(0x1F562, new String[]{"clock730"}, false),
      new GoogleCompatEmoji(0x1F557, new String[]{"clock8"}, false),
      new GoogleCompatEmoji(0x1F563, new String[]{"clock830"}, false),
      new GoogleCompatEmoji(0x1F558, new String[]{"clock9"}, false),
      new GoogleCompatEmoji(0x1F564, new String[]{"clock930"}, false),
      new GoogleCompatEmoji(0x1F559, new String[]{"clock10"}, false),
      new GoogleCompatEmoji(0x1F565, new String[]{"clock1030"}, false),
      new GoogleCompatEmoji(0x1F55A, new String[]{"clock11"}, false),
      new GoogleCompatEmoji(0x1F566, new String[]{"clock1130"}, false),
      new GoogleCompatEmoji(0x1F311, new String[]{"new_moon"}, false),
      new GoogleCompatEmoji(0x1F312, new String[]{"waxing_crescent_moon"}, false),
      new GoogleCompatEmoji(0x1F313, new String[]{"first_quarter_moon"}, false),
      new GoogleCompatEmoji(0x1F314, new String[]{"moon", "waxing_gibbous_moon"}, false),
      new GoogleCompatEmoji(0x1F315, new String[]{"full_moon"}, false),
      new GoogleCompatEmoji(0x1F316, new String[]{"waning_gibbous_moon"}, false),
      new GoogleCompatEmoji(0x1F317, new String[]{"last_quarter_moon"}, false),
      new GoogleCompatEmoji(0x1F318, new String[]{"waning_crescent_moon"}, false),
      new GoogleCompatEmoji(0x1F319, new String[]{"crescent_moon"}, false),
      new GoogleCompatEmoji(0x1F31A, new String[]{"new_moon_with_face"}, false),
      new GoogleCompatEmoji(0x1F31B, new String[]{"first_quarter_moon_with_face"}, false),
      new GoogleCompatEmoji(0x1F31C, new String[]{"last_quarter_moon_with_face"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F321, 0xFE0F }, new String[]{"thermometer"}, false),
      new GoogleCompatEmoji(new int[] { 0x2600, 0xFE0F }, new String[]{"sunny"}, false),
      new GoogleCompatEmoji(0x1F31D, new String[]{"full_moon_with_face"}, false),
      new GoogleCompatEmoji(0x1F31E, new String[]{"sun_with_face"}, false),
      new GoogleCompatEmoji(0x1FA90, new String[]{"ringed_planet"}, false),
      new GoogleCompatEmoji(0x2B50, new String[]{"star"}, false),
      new GoogleCompatEmoji(0x1F31F, new String[]{"star2"}, false),
      new GoogleCompatEmoji(0x1F320, new String[]{"stars"}, false),
      new GoogleCompatEmoji(0x1F30C, new String[]{"milky_way"}, false),
      new GoogleCompatEmoji(new int[] { 0x2601, 0xFE0F }, new String[]{"cloud"}, false),
      new GoogleCompatEmoji(0x26C5, new String[]{"partly_sunny"}, false),
      new GoogleCompatEmoji(new int[] { 0x26C8, 0xFE0F }, new String[]{"thunder_cloud_and_rain"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F324, 0xFE0F }, new String[]{"mostly_sunny", "sun_small_cloud"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F325, 0xFE0F }, new String[]{"barely_sunny", "sun_behind_cloud"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F326, 0xFE0F }, new String[]{"partly_sunny_rain", "sun_behind_rain_cloud"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F327, 0xFE0F }, new String[]{"rain_cloud"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F328, 0xFE0F }, new String[]{"snow_cloud"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F329, 0xFE0F }, new String[]{"lightning", "lightning_cloud"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F32A, 0xFE0F }, new String[]{"tornado", "tornado_cloud"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F32B, 0xFE0F }, new String[]{"fog"}, false),
      new GoogleCompatEmoji(new int[] { 0x1F32C, 0xFE0F }, new String[]{"wind_blowing_face"}, false),
      new GoogleCompatEmoji(0x1F300, new String[]{"cyclone"}, false),
      new GoogleCompatEmoji(0x1F308, new String[]{"rainbow"}, false),
      new GoogleCompatEmoji(0x1F302, new String[]{"closed_umbrella"}, false),
      new GoogleCompatEmoji(new int[] { 0x2602, 0xFE0F }, new String[]{"umbrella"}, false),
      new GoogleCompatEmoji(0x2614, new String[]{"umbrella_with_rain_drops"}, false),
      new GoogleCompatEmoji(new int[] { 0x26F1, 0xFE0F }, new String[]{"umbrella_on_ground"}, false),
      new GoogleCompatEmoji(0x26A1, new String[]{"zap"}, false),
      new GoogleCompatEmoji(new int[] { 0x2744, 0xFE0F }, new String[]{"snowflake"}, false),
      new GoogleCompatEmoji(new int[] { 0x2603, 0xFE0F }, new String[]{"snowman"}, false),
      new GoogleCompatEmoji(0x26C4, new String[]{"snowman_without_snow"}, false),
      new GoogleCompatEmoji(new int[] { 0x2604, 0xFE0F }, new String[]{"comet"}, false),
      new GoogleCompatEmoji(0x1F525, new String[]{"fire"}, false),
      new GoogleCompatEmoji(0x1F4A7, new String[]{"droplet"}, false),
      new GoogleCompatEmoji(0x1F30A, new String[]{"ocean"}, false)
    };
  }

  private TravelAndPlacesCategoryChunk0() {
    // No instances.
  }
}
