package com.vanniktech.emoji.googlecompat.category;

import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;

final class TravelAndPlacesCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleCompatEmoji[] get() {
    return new GoogleCompatEmoji[] {
      new GoogleCompatEmoji(0x1F30D, false),
      new GoogleCompatEmoji(0x1F30E, false),
      new GoogleCompatEmoji(0x1F30F, false),
      new GoogleCompatEmoji(0x1F310, false),
      new GoogleCompatEmoji(new int[] { 0x1F5FA, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F5FE, false),
      new GoogleCompatEmoji(0x1F9ED, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D4, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x26F0, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F30B, false),
      new GoogleCompatEmoji(0x1F5FB, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D5, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D6, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DC, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DD, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DE, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DF, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DB, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D7, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F9F1, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D8, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3DA, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3E0, false),
      new GoogleCompatEmoji(0x1F3E1, false),
      new GoogleCompatEmoji(0x1F3E2, false),
      new GoogleCompatEmoji(0x1F3E3, false),
      new GoogleCompatEmoji(0x1F3E4, false),
      new GoogleCompatEmoji(0x1F3E5, false),
      new GoogleCompatEmoji(0x1F3E6, false),
      new GoogleCompatEmoji(0x1F3E8, false),
      new GoogleCompatEmoji(0x1F3E9, false),
      new GoogleCompatEmoji(0x1F3EA, false),
      new GoogleCompatEmoji(0x1F3EB, false),
      new GoogleCompatEmoji(0x1F3EC, false),
      new GoogleCompatEmoji(0x1F3ED, false),
      new GoogleCompatEmoji(0x1F3EF, false),
      new GoogleCompatEmoji(0x1F3F0, false),
      new GoogleCompatEmoji(0x1F492, false),
      new GoogleCompatEmoji(0x1F5FC, false),
      new GoogleCompatEmoji(0x1F5FD, false),
      new GoogleCompatEmoji(0x26EA, false),
      new GoogleCompatEmoji(0x1F54C, false),
      new GoogleCompatEmoji(0x1F6D5, false),
      new GoogleCompatEmoji(0x1F54D, false),
      new GoogleCompatEmoji(new int[] { 0x26E9, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F54B, false),
      new GoogleCompatEmoji(0x26F2, false),
      new GoogleCompatEmoji(0x26FA, false),
      new GoogleCompatEmoji(0x1F301, false),
      new GoogleCompatEmoji(0x1F303, false),
      new GoogleCompatEmoji(new int[] { 0x1F3D9, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F304, false),
      new GoogleCompatEmoji(0x1F305, false),
      new GoogleCompatEmoji(0x1F306, false),
      new GoogleCompatEmoji(0x1F307, false),
      new GoogleCompatEmoji(0x1F309, false),
      new GoogleCompatEmoji(new int[] { 0x2668, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F3A0, false),
      new GoogleCompatEmoji(0x1F3A1, false),
      new GoogleCompatEmoji(0x1F3A2, false),
      new GoogleCompatEmoji(0x1F488, false),
      new GoogleCompatEmoji(0x1F3AA, false),
      new GoogleCompatEmoji(0x1F682, false),
      new GoogleCompatEmoji(0x1F683, false),
      new GoogleCompatEmoji(0x1F684, false),
      new GoogleCompatEmoji(0x1F685, false),
      new GoogleCompatEmoji(0x1F686, false),
      new GoogleCompatEmoji(0x1F687, false),
      new GoogleCompatEmoji(0x1F688, false),
      new GoogleCompatEmoji(0x1F689, false),
      new GoogleCompatEmoji(0x1F68A, false),
      new GoogleCompatEmoji(0x1F69D, false),
      new GoogleCompatEmoji(0x1F69E, false),
      new GoogleCompatEmoji(0x1F68B, false),
      new GoogleCompatEmoji(0x1F68C, false),
      new GoogleCompatEmoji(0x1F68D, false),
      new GoogleCompatEmoji(0x1F68E, false),
      new GoogleCompatEmoji(0x1F690, false),
      new GoogleCompatEmoji(0x1F691, false),
      new GoogleCompatEmoji(0x1F692, false),
      new GoogleCompatEmoji(0x1F693, false),
      new GoogleCompatEmoji(0x1F694, false),
      new GoogleCompatEmoji(0x1F695, false),
      new GoogleCompatEmoji(0x1F696, false),
      new GoogleCompatEmoji(0x1F697, false),
      new GoogleCompatEmoji(0x1F698, false),
      new GoogleCompatEmoji(0x1F699, false),
      new GoogleCompatEmoji(0x1F69A, false),
      new GoogleCompatEmoji(0x1F69B, false),
      new GoogleCompatEmoji(0x1F69C, false),
      new GoogleCompatEmoji(new int[] { 0x1F3CE, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F3CD, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F6F5, false),
      new GoogleCompatEmoji(0x1F9BD, false),
      new GoogleCompatEmoji(0x1F9BC, false),
      new GoogleCompatEmoji(0x1F6FA, false),
      new GoogleCompatEmoji(0x1F6B2, false),
      new GoogleCompatEmoji(0x1F6F4, false),
      new GoogleCompatEmoji(0x1F6F9, false),
      new GoogleCompatEmoji(0x1F68F, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E3, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E4, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E2, 0xFE0F }, false),
      new GoogleCompatEmoji(0x26FD, false),
      new GoogleCompatEmoji(0x1F6A8, false),
      new GoogleCompatEmoji(0x1F6A5, false),
      new GoogleCompatEmoji(0x1F6A6, false),
      new GoogleCompatEmoji(0x1F6D1, false),
      new GoogleCompatEmoji(0x1F6A7, false),
      new GoogleCompatEmoji(0x2693, false),
      new GoogleCompatEmoji(0x26F5, false),
      new GoogleCompatEmoji(0x1F6F6, false),
      new GoogleCompatEmoji(0x1F6A4, false),
      new GoogleCompatEmoji(new int[] { 0x1F6F3, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x26F4, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E5, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F6A2, false),
      new GoogleCompatEmoji(new int[] { 0x2708, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F6E9, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F6EB, false),
      new GoogleCompatEmoji(0x1F6EC, false),
      new GoogleCompatEmoji(0x1FA82, false),
      new GoogleCompatEmoji(0x1F4BA, false),
      new GoogleCompatEmoji(0x1F681, false),
      new GoogleCompatEmoji(0x1F69F, false),
      new GoogleCompatEmoji(0x1F6A0, false),
      new GoogleCompatEmoji(0x1F6A1, false),
      new GoogleCompatEmoji(new int[] { 0x1F6F0, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F680, false),
      new GoogleCompatEmoji(0x1F6F8, false),
      new GoogleCompatEmoji(new int[] { 0x1F6CE, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F9F3, false),
      new GoogleCompatEmoji(0x231B, false),
      new GoogleCompatEmoji(0x23F3, false),
      new GoogleCompatEmoji(0x231A, false),
      new GoogleCompatEmoji(0x23F0, false),
      new GoogleCompatEmoji(new int[] { 0x23F1, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x23F2, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F570, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F55B, false),
      new GoogleCompatEmoji(0x1F567, false),
      new GoogleCompatEmoji(0x1F550, false),
      new GoogleCompatEmoji(0x1F55C, false),
      new GoogleCompatEmoji(0x1F551, false),
      new GoogleCompatEmoji(0x1F55D, false),
      new GoogleCompatEmoji(0x1F552, false),
      new GoogleCompatEmoji(0x1F55E, false),
      new GoogleCompatEmoji(0x1F553, false),
      new GoogleCompatEmoji(0x1F55F, false),
      new GoogleCompatEmoji(0x1F554, false),
      new GoogleCompatEmoji(0x1F560, false),
      new GoogleCompatEmoji(0x1F555, false),
      new GoogleCompatEmoji(0x1F561, false),
      new GoogleCompatEmoji(0x1F556, false),
      new GoogleCompatEmoji(0x1F562, false),
      new GoogleCompatEmoji(0x1F557, false),
      new GoogleCompatEmoji(0x1F563, false),
      new GoogleCompatEmoji(0x1F558, false),
      new GoogleCompatEmoji(0x1F564, false),
      new GoogleCompatEmoji(0x1F559, false),
      new GoogleCompatEmoji(0x1F565, false),
      new GoogleCompatEmoji(0x1F55A, false),
      new GoogleCompatEmoji(0x1F566, false),
      new GoogleCompatEmoji(0x1F311, false),
      new GoogleCompatEmoji(0x1F312, false),
      new GoogleCompatEmoji(0x1F313, false),
      new GoogleCompatEmoji(0x1F314, false),
      new GoogleCompatEmoji(0x1F315, false),
      new GoogleCompatEmoji(0x1F316, false),
      new GoogleCompatEmoji(0x1F317, false),
      new GoogleCompatEmoji(0x1F318, false),
      new GoogleCompatEmoji(0x1F319, false),
      new GoogleCompatEmoji(0x1F31A, false),
      new GoogleCompatEmoji(0x1F31B, false),
      new GoogleCompatEmoji(0x1F31C, false),
      new GoogleCompatEmoji(new int[] { 0x1F321, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2600, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F31D, false),
      new GoogleCompatEmoji(0x1F31E, false),
      new GoogleCompatEmoji(0x1FA90, false),
      new GoogleCompatEmoji(0x2B50, false),
      new GoogleCompatEmoji(0x1F31F, false),
      new GoogleCompatEmoji(0x1F320, false),
      new GoogleCompatEmoji(0x1F30C, false),
      new GoogleCompatEmoji(new int[] { 0x2601, 0xFE0F }, false),
      new GoogleCompatEmoji(0x26C5, false),
      new GoogleCompatEmoji(new int[] { 0x26C8, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F324, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F325, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F326, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F327, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F328, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F329, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F32A, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F32B, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x1F32C, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F300, false),
      new GoogleCompatEmoji(0x1F308, false),
      new GoogleCompatEmoji(0x1F302, false),
      new GoogleCompatEmoji(new int[] { 0x2602, 0xFE0F }, false),
      new GoogleCompatEmoji(0x2614, false),
      new GoogleCompatEmoji(new int[] { 0x26F1, 0xFE0F }, false),
      new GoogleCompatEmoji(0x26A1, false),
      new GoogleCompatEmoji(new int[] { 0x2744, 0xFE0F }, false),
      new GoogleCompatEmoji(new int[] { 0x2603, 0xFE0F }, false),
      new GoogleCompatEmoji(0x26C4, false),
      new GoogleCompatEmoji(new int[] { 0x2604, 0xFE0F }, false),
      new GoogleCompatEmoji(0x1F525, false),
      new GoogleCompatEmoji(0x1F4A7, false),
      new GoogleCompatEmoji(0x1F30A, false)
    };
  }

  private TravelAndPlacesCategoryChunk0() {
    // No instances.
  }
}
